/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraphSearchRouteImport } from './routes/graph-search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioDdIndexRouteImport } from './routes/portfolio-dd/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as PortfolioDdReviewIdRouteImport } from './routes/portfolio-dd/$reviewId'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as PortfolioDdReviewIdReportRouteImport } from './routes/portfolio-dd/$reviewId/report'
import { Route as ClientsClientIdReportRouteImport } from './routes/clients/$clientId/report'

const GraphSearchRoute = GraphSearchRouteImport.update({
  id: '/graph-search',
  path: '/graph-search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioDdIndexRoute = PortfolioDdIndexRouteImport.update({
  id: '/portfolio-dd/',
  path: '/portfolio-dd/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioDdReviewIdRoute = PortfolioDdReviewIdRouteImport.update({
  id: '/portfolio-dd/$reviewId',
  path: '/portfolio-dd/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioDdReviewIdReportRoute =
  PortfolioDdReviewIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => PortfolioDdReviewIdRoute,
  } as any)
const ClientsClientIdReportRoute = ClientsClientIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ClientsClientIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph-search': typeof GraphSearchRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/portfolio-dd/$reviewId': typeof PortfolioDdReviewIdRouteWithChildren
  '/clients/': typeof ClientsIndexRoute
  '/portfolio-dd/': typeof PortfolioDdIndexRoute
  '/clients/$clientId/report': typeof ClientsClientIdReportRoute
  '/portfolio-dd/$reviewId/report': typeof PortfolioDdReviewIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph-search': typeof GraphSearchRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/portfolio-dd/$reviewId': typeof PortfolioDdReviewIdRouteWithChildren
  '/clients': typeof ClientsIndexRoute
  '/portfolio-dd': typeof PortfolioDdIndexRoute
  '/clients/$clientId/report': typeof ClientsClientIdReportRoute
  '/portfolio-dd/$reviewId/report': typeof PortfolioDdReviewIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph-search': typeof GraphSearchRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/portfolio-dd/$reviewId': typeof PortfolioDdReviewIdRouteWithChildren
  '/clients/': typeof ClientsIndexRoute
  '/portfolio-dd/': typeof PortfolioDdIndexRoute
  '/clients/$clientId/report': typeof ClientsClientIdReportRoute
  '/portfolio-dd/$reviewId/report': typeof PortfolioDdReviewIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph-search'
    | '/clients/$clientId'
    | '/portfolio-dd/$reviewId'
    | '/clients/'
    | '/portfolio-dd/'
    | '/clients/$clientId/report'
    | '/portfolio-dd/$reviewId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph-search'
    | '/clients/$clientId'
    | '/portfolio-dd/$reviewId'
    | '/clients'
    | '/portfolio-dd'
    | '/clients/$clientId/report'
    | '/portfolio-dd/$reviewId/report'
  id:
    | '__root__'
    | '/'
    | '/graph-search'
    | '/clients/$clientId'
    | '/portfolio-dd/$reviewId'
    | '/clients/'
    | '/portfolio-dd/'
    | '/clients/$clientId/report'
    | '/portfolio-dd/$reviewId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphSearchRoute: typeof GraphSearchRoute
  ClientsClientIdRoute: typeof ClientsClientIdRouteWithChildren
  PortfolioDdReviewIdRoute: typeof PortfolioDdReviewIdRouteWithChildren
  ClientsIndexRoute: typeof ClientsIndexRoute
  PortfolioDdIndexRoute: typeof PortfolioDdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/graph-search': {
      id: '/graph-search'
      path: '/graph-search'
      fullPath: '/graph-search'
      preLoaderRoute: typeof GraphSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-dd/': {
      id: '/portfolio-dd/'
      path: '/portfolio-dd'
      fullPath: '/portfolio-dd/'
      preLoaderRoute: typeof PortfolioDdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-dd/$reviewId': {
      id: '/portfolio-dd/$reviewId'
      path: '/portfolio-dd/$reviewId'
      fullPath: '/portfolio-dd/$reviewId'
      preLoaderRoute: typeof PortfolioDdReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-dd/$reviewId/report': {
      id: '/portfolio-dd/$reviewId/report'
      path: '/report'
      fullPath: '/portfolio-dd/$reviewId/report'
      preLoaderRoute: typeof PortfolioDdReviewIdReportRouteImport
      parentRoute: typeof PortfolioDdReviewIdRoute
    }
    '/clients/$clientId/report': {
      id: '/clients/$clientId/report'
      path: '/report'
      fullPath: '/clients/$clientId/report'
      preLoaderRoute: typeof ClientsClientIdReportRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
  }
}

interface ClientsClientIdRouteChildren {
  ClientsClientIdReportRoute: typeof ClientsClientIdReportRoute
}

const ClientsClientIdRouteChildren: ClientsClientIdRouteChildren = {
  ClientsClientIdReportRoute: ClientsClientIdReportRoute,
}

const ClientsClientIdRouteWithChildren = ClientsClientIdRoute._addFileChildren(
  ClientsClientIdRouteChildren,
)

interface PortfolioDdReviewIdRouteChildren {
  PortfolioDdReviewIdReportRoute: typeof PortfolioDdReviewIdReportRoute
}

const PortfolioDdReviewIdRouteChildren: PortfolioDdReviewIdRouteChildren = {
  PortfolioDdReviewIdReportRoute: PortfolioDdReviewIdReportRoute,
}

const PortfolioDdReviewIdRouteWithChildren =
  PortfolioDdReviewIdRoute._addFileChildren(PortfolioDdReviewIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphSearchRoute: GraphSearchRoute,
  ClientsClientIdRoute: ClientsClientIdRouteWithChildren,
  PortfolioDdReviewIdRoute: PortfolioDdReviewIdRouteWithChildren,
  ClientsIndexRoute: ClientsIndexRoute,
  PortfolioDdIndexRoute: PortfolioDdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
