"""Generate source documents for pf_macq001 -- Macquarie Income Fund."""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from pdf_helpers import DocPDF


def gen_pds():
    pdf = DocPDF("Macquarie Income Fund - PDS")
    pdf.cover_page("Macquarie Income Fund", "Product Disclosure Statement", "1 January 2026", "Macquarie Investment Management Limited")

    pdf.add_page()
    pdf.section("1. About Macquarie Investment Management")
    pdf.body("Macquarie Investment Management Limited (ABN 66 002 867 003, AFSL 237492) is the responsible entity and investment manager of the Macquarie Income Fund. Macquarie Investment Management is a division of Macquarie Asset Management, part of the Macquarie Group (ASX: MQG).")
    pdf.table_row("ABN", "66 002 867 003")
    pdf.table_row("AFSL", "237492")
    pdf.table_row("Founded", "1969")
    pdf.table_row("Headquarters", "Sydney, NSW")
    pdf.table_row("Division AUM", "AUD 643 billion (global)")
    pdf.table_row("Parent", "Macquarie Group Limited (ASX: MQG)")
    pdf.body("AFSL 237492 is current and in good standing. There have been no enforceable undertakings issued by ASIC against Macquarie Investment Management Limited in relation to this fund. The firm operates within a robust compliance framework overseen by the Macquarie Group's Risk Management Division.")
    pdf.body("Macquarie Group is one of Australia's premier financial institutions, listed on the ASX with a market capitalisation exceeding AUD 80 billion. The Asset Management division benefits from the group's global infrastructure, technology, and risk management capabilities.")

    pdf.add_page()
    pdf.section("2. Investment Philosophy & Process")
    pdf.body("The Macquarie Income Fund is a conservative fixed income fund designed to provide investors with a regular income stream while preserving capital. The fund targets returns above the Bloomberg AusBond Bank Bill Index over rolling 1-year periods.")
    pdf.body("Investment philosophy:")
    pdf.bullet("Capital preservation is the primary objective. Income generation is secondary to protecting investors' capital.")
    pdf.bullet("Credit risk is the primary source of incremental return above cash. Duration risk is actively managed but kept short.")
    pdf.bullet("Disciplined, process-driven approach with rigorous credit research reduces the risk of permanent capital impairment from defaults.")
    pdf.subsection("Alpha Sources")
    pdf.body("The fund targets modest excess return over the benchmark through: (1) credit selection -- investing in investment-grade and select sub-investment-grade corporate bonds offering attractive spreads relative to default risk, (2) duration management -- modest tactical adjustments to portfolio duration based on interest rate outlook, and (3) yield curve positioning -- exploiting relative value along the yield curve.")
    pdf.subsection("Process Evolution")
    pdf.body("The investment process was enhanced in 2022 with the introduction of proprietary quantitative credit scoring models. These models complement fundamental credit research and provide early warning signals on deteriorating credit quality. The fund's duration management approach was tightened in 2023 following the rapid rate-hiking cycle, with the maximum deviation from benchmark duration reduced from +/-1.5 years to +/-1.0 year.")

    pdf.add_page()
    pdf.section("3. Portfolio Construction")
    pdf.body("The fund constructs a diversified portfolio of Australian dollar-denominated fixed income securities:")
    pdf.subsection("Portfolio Parameters")
    pdf.table_row("Target Duration", "0.0 - 1.5 years (benchmark: ~0.2 years)")
    pdf.table_row("Max Duration Deviation", "+/- 1.0 year vs benchmark")
    pdf.table_row("Credit Quality (min)", "BBB- (investment grade)")
    pdf.table_row("Sub-IG Allowance", "Max 5% of portfolio")
    pdf.table_row("Single Issuer Limit", "5% (excl. Commonwealth/State govt)")
    pdf.table_row("Single Sector Limit", "30%")
    pdf.table_row("Min Liquidity (7-day)", "50% of portfolio")
    pdf.table_row("Max Maturity (single)", "5 years")
    pdf.subsection("Asset Allocation Ranges")
    pdf.table_row("Bank Deposits & Bills", "20-60%")
    pdf.table_row("Corporate Bonds (IG)", "20-50%")
    pdf.table_row("Government/Semi-Govt", "10-40%")
    pdf.table_row("Asset-Backed Securities", "0-20%")
    pdf.table_row("Sub-Investment Grade", "0-5%")
    pdf.body("The fund does not use leverage or derivatives except for interest rate futures to manage portfolio duration within permitted ranges.")

    pdf.add_page()
    pdf.section("4. Benchmark & Objectives")
    pdf.table_row("Benchmark", "Bloomberg AusBond Bank Bill Index")
    pdf.table_row("Return Objective", "Benchmark + 0.50% p.a. (after fees)")
    pdf.table_row("Risk Objective", "No negative quarterly return")
    pdf.table_row("Time Horizon", "Rolling 1-year periods")
    pdf.body("The Bloomberg AusBond Bank Bill Index is a widely used benchmark for Australian short-term fixed income investments. It represents the return on a portfolio of bank-accepted bills and negotiable certificates of deposit.")
    pdf.body("The benchmark is appropriate because: (1) it reflects the fund's short-duration, income-focused mandate, (2) it is widely used by peers in the enhanced cash/short-term fixed income category, (3) it has been used since the fund's inception in November 2000 with no changes, and (4) its composition (bank bills) closely matches the fund's credit quality and duration characteristics.")

    pdf.add_page()
    pdf.section("5. Key Personnel")
    pdf.subsection("Ben Way -- Group Head, Macquarie Asset Management")
    pdf.body("Ben Way is the Group Head of Macquarie Asset Management, overseeing all investment management activities globally. He has over 30 years of experience in financial services and has been with Macquarie since 1993.")
    pdf.subsection("Fixed Income Team")
    pdf.body("The Australian Fixed Income team responsible for this fund comprises:")
    pdf.bullet("Head of Australian Fixed Income (22 years experience, 14 years at Macquarie)")
    pdf.bullet("2 Senior Portfolio Managers (average 18 years experience)")
    pdf.bullet("4 Credit Analysts (covering financials, industrials, utilities, ABS)")
    pdf.bullet("2 Rates/Duration Strategists")
    pdf.bullet("1 Portfolio Implementation Specialist")
    pdf.table_row("Team size", "10 dedicated professionals")
    pdf.table_row("Average tenure", "11.3 years")
    pdf.table_row("Average experience", "17 years")
    pdf.body("Key person: The Head of Australian Fixed Income is identified as the key person for this fund. Succession plan: The two Senior PMs have co-signing authority and full capability to manage the fund independently. All credit research is team-based with multiple analyst coverage per sector.")

    pdf.add_page()
    pdf.section("6. ESG Integration")
    pdf.body("Macquarie Asset Management is a UNPRI signatory (since 2014). ESG integration in the fixed income process includes:")
    pdf.bullet("Credit research incorporates ESG risk assessment for all issuers (governance and environmental factors can affect credit quality)")
    pdf.bullet("Exclusions: Controversial weapons manufacturers, companies deriving >10% revenue from thermal coal mining")
    pdf.bullet("Green bonds: The fund may invest in certified green bonds where credit quality meets requirements")
    pdf.bullet("Engagement: Active engagement with issuers on governance and sustainability disclosure")
    pdf.bullet("Climate: Portfolio exposure to carbon-intensive industries is monitored and disclosed quarterly")
    pdf.body("UNPRI Assessment (most recent): A for Fixed Income -- SSA, A for Fixed Income -- Corporate.")

    pdf.add_page()
    pdf.section("7. Conflicts of Interest")
    pdf.body("Macquarie's Conflicts of Interest framework:")
    pdf.bullet("Related parties: The fund may hold securities issued by Macquarie Group or affiliates, subject to independent approval and the same credit assessment process as any other issuer. Related-party holdings are disclosed in the annual report.")
    pdf.bullet("Personal trading: All investment staff subject to Macquarie Group's personal account dealing policy (pre-clearance, 30-day hold, blackout periods)")
    pdf.bullet("Soft dollars: Not accepted. All research paid from firm P&L.")
    pdf.bullet("Trade allocation: Pro-rata allocation across all Macquarie fixed income funds. New issue allocations follow a documented fair allocation policy reviewed by Compliance.")
    pdf.bullet("Board: The Responsible Entity Board has majority independent directors (5 of 7). Investment decisions are made by the investment team, not the Board.")

    pdf.add_page()
    pdf.section("8. Fees & Costs")
    pdf.table_row("Management Fee (MER)", "0.28% p.a. of NAV")
    pdf.table_row("Indirect Cost Ratio (ICR)", "0.01% p.a.")
    pdf.table_row("Performance Fee", "Nil")
    pdf.table_row("Buy Spread", "0.00%")
    pdf.table_row("Sell Spread", "0.05%")
    pdf.table_row("Entry/Exit Fees", "Nil")
    pdf.body("The Management Fee of 0.28% p.a. is one of the lowest in the enhanced cash/short-term fixed income category, reflecting the fund's scale (AUD 4.2 billion) and Macquarie's commitment to competitive pricing for income investors.")
    pdf.body("The minimal buy spread (zero) and low sell spread (0.05%) reflect the high liquidity of the underlying portfolio. The sell spread compensates existing investors for the small transaction costs of liquidating positions to meet redemptions.")
    pdf.body("Total estimated cost: 0.29% p.a. plus 0.05% sell spread on exit.")

    pdf.add_page()
    pdf.section("9. Business Viability")
    pdf.table_row("Fund AUM", "AUD 4,200 million")
    pdf.table_row("Fund Inception", "30 November 2000")
    pdf.table_row("APIR Code", "MAQ0045AU")
    pdf.table_row("Macquarie AM Total AUM", "AUD 643 billion (global)")
    pdf.table_row("Australian Fixed Income AUM", "AUD 32 billion")
    pdf.table_row("Parent Market Cap", "~AUD 80 billion (MQG)")
    pdf.body("The Macquarie Income Fund is one of the largest short-term fixed income funds in Australia. At AUD 4.2 billion, the fund benefits from significant economies of scale, enabling a low management fee while supporting a dedicated 10-person investment team.")
    pdf.body("Macquarie Group's financial strength (AA- credit rating, market cap ~AUD 80B) provides exceptional counterparty and operational stability. There are no indicators of fund wind-down risk.")
    pdf.subsection("AUM Trend")
    pdf.table_row("Dec 2023", "AUD 3,800 million")
    pdf.table_row("Dec 2024", "AUD 4,050 million")
    pdf.table_row("Dec 2025", "AUD 4,200 million")
    pdf.table_row("3-Year CAGR", "+6.8%")
    pdf.body("Consistent net inflows driven by institutional demand for quality short-duration income strategies.")

    # Pad to ~28 pages
    for i in range(18):
        pdf.add_page()
        if i == 0:
            pdf.section("10. Risk Disclosures")
            pdf.body("Key risks of investing in the Macquarie Income Fund:")
            pdf.bullet("Credit risk: The risk that a bond issuer defaults on interest or principal payments. Mitigated by investment-grade focus and diversification.")
            pdf.bullet("Interest rate risk: Bond prices fall when rates rise. Mitigated by short duration (0-1.5 years) and active duration management.")
            pdf.bullet("Liquidity risk: The risk that securities cannot be sold at fair value. Mitigated by 50% minimum 7-day liquidity requirement.")
            pdf.bullet("Counterparty risk: Managed through ISDA agreements and daily margining on any derivative positions.")
        elif i == 1:
            pdf.subsection("Risk Metrics (Target)")
            pdf.table_row("Portfolio Duration", "0.0 - 1.5 years")
            pdf.table_row("Credit Duration", "0.5 - 2.0 years")
            pdf.table_row("Tracking Error vs Benchmark", "< 0.5% p.a.")
            pdf.table_row("Value-at-Risk (95%, 1-day)", "< 0.05% of NAV")
            pdf.table_row("Expected Max Drawdown", "< -0.5% (quarterly)")
        elif i == 2:
            pdf.section("11. Regulatory Information")
            pdf.body("Macquarie Investment Management Limited holds AFSL 237492:")
            pdf.bullet("Licence is current and in good standing")
            pdf.bullet("Authorised to operate managed investment schemes")
            pdf.bullet("ARSN: 090 079 167")
            pdf.bullet("No enforceable undertakings in past 10 years")
            pdf.bullet("No material regulatory actions or proceedings")
            pdf.bullet("AFCA member")
            pdf.body("The fund operates within Macquarie Group's comprehensive regulatory compliance framework, which is subject to oversight by ASIC, APRA, and international regulators in each jurisdiction of operation.")
        elif i == 3:
            pdf.section("12. Compliance Framework")
            pdf.body("Macquarie's compliance function benefits from the group's global scale:")
            pdf.bullet("Dedicated compliance team for Asset Management (15 professionals in Australia)")
            pdf.bullet("Group Compliance oversight and coordination")
            pdf.bullet("Automated pre-trade compliance via Bloomberg AIM")
            pdf.bullet("Monthly compliance reporting to RE Board")
            pdf.bullet("Annual compliance plan (Board-approved January 2026)")
            pdf.bullet("Mandatory training: 100% completion rate")
            pdf.body("Breach register: Zero breaches relating to the Income Fund in the past 3 years. Two minor operational breaches across the broader fixed income platform (both self-identified, no client impact).")
        elif i == 4:
            pdf.section("13. Governance Structure")
            pdf.body("The Macquarie Income Fund's governance:")
            pdf.bullet("Responsible Entity Board: 7 directors, 5 independent")
            pdf.bullet("Investment Committee: Head of Fixed Income + 2 Senior PMs + CRO")
            pdf.bullet("Credit Committee: Approves all new credit exposures")
            pdf.bullet("Product Governance Committee: Oversees fund operations")
            pdf.bullet("Board Risk Committee: Independent oversight of risk framework")
        elif i == 5:
            pdf.section("14. Operational Risk Management")
            pdf.body("Key operational controls:")
            pdf.bullet("Daily independent reconciliation (Macquarie vs custodian)")
            pdf.bullet("Independent pricing verification (Bloomberg/ICE feeds)")
            pdf.bullet("Segregation of duties: Front office / Middle office / Back office")
            pdf.bullet("Dual authorisation for all payments and settlements")
            pdf.bullet("ISAE 3402 reports from custodian and administrator")
        elif i == 6:
            pdf.section("15. Custodian & Administration")
            pdf.body("Fund custodian: National Australia Bank Limited (NAB) -- an APRA-regulated ADI.")
            pdf.table_row("Custodian", "NAB (APRA-regulated)")
            pdf.table_row("Administrator", "NAB Asset Servicing")
            pdf.table_row("Registry", "Link Market Services")
            pdf.table_row("Auditor", "PricewaterhouseCoopers (PwC)")
            pdf.body("NAB as custodian provides segregation of fund assets from Macquarie Group's own assets, ensuring investor protection in the unlikely event of Macquarie's insolvency.")
        elif i == 7:
            pdf.section("16. Business Continuity")
            pdf.table_row("RTO", "2 hours for trading systems")
            pdf.table_row("RPO", "15 minutes (real-time data replication)")
            pdf.table_row("DR Sites", "Multiple (Sydney CBD, Parramatta, Melbourne)")
            pdf.body("Macquarie Group's global infrastructure provides exceptional resilience:")
            pdf.bullet("Multiple geographically diverse data centres")
            pdf.bullet("Full hot-standby capability at DR sites")
            pdf.bullet("Quarterly BCP/DR testing (last: November 2025)")
            pdf.bullet("COVID validation: Uninterrupted operations throughout 2020-21")
            pdf.body("The firm's BCP has been tested and proven effective through multiple real-world events including natural disasters, technology failures, and the pandemic.")
        elif i == 8:
            pdf.section("17. Taxation")
            pdf.body("The fund operates under the AMIT regime. Distributions are made monthly, comprising interest income and any realised capital gains. Monthly distributions provide regular income to investors, consistent with the fund's income-focused mandate.")
        elif i == 9:
            pdf.section("18. Withdrawals")
            pdf.body("Daily liquidity: Withdrawal requests lodged before 12pm AEST are processed at that day's unit price. Payment typically within 2-3 business days. The fund's high liquidity profile (50%+ realisable in 7 days) supports daily redemptions without gates or notice periods under normal market conditions.")
        elif i == 10:
            pdf.section("19. Derivatives Use")
            pdf.body("The fund may use the following derivatives for risk management purposes only:")
            pdf.bullet("Interest rate futures: To manage portfolio duration within permitted ranges")
            pdf.bullet("No credit derivatives (no CDS)")
            pdf.bullet("No currency derivatives (AUD-denominated securities only)")
            pdf.bullet("No options or structured products")
            pdf.body("Derivative positions are margined daily and do not create leverage. Gross derivative exposure is limited to 20% of NAV for duration management purposes.")
        elif i == 11:
            pdf.section("20. Credit Research Process")
            pdf.body("The fund's credit research process:")
            pdf.bullet("Initial screening: Quantitative credit score (proprietary model)")
            pdf.bullet("Fundamental analysis: Financial statement review, management assessment, industry dynamics")
            pdf.bullet("ESG overlay: Governance and environmental risk factors")
            pdf.bullet("Credit Committee approval: All new positions require formal approval")
            pdf.bullet("Ongoing monitoring: Quarterly credit reviews, automated alert triggers")
            pdf.body("The team covers approximately 200 Australian issuers, with each analyst responsible for 40-50 credits across their assigned sectors.")
        elif i == 12:
            pdf.section("21. Counterparty Management")
            pdf.body("Counterparty risk controls:")
            pdf.table_row("Min counterparty rating", "A- (for OTC transactions)")
            pdf.table_row("ISDA agreements", "In place with all derivative counterparties")
            pdf.table_row("Daily margining", "Required for all OTC positions")
            pdf.table_row("Exposure limits", "Monitored and reported daily")
            pdf.body("The fund's counterparty exposure is minimal given the focus on direct bond holdings and exchange-traded futures.")
        elif i == 13:
            pdf.section("22. Valuation Policy")
            pdf.body("Securities are valued daily using independent pricing sources:")
            pdf.bullet("Government bonds: Bloomberg/AOFM pricing")
            pdf.bullet("Corporate bonds: Bloomberg BVAL / ICE")
            pdf.bullet("Bank deposits: Amortised cost (appropriate for short-dated instruments)")
            pdf.bullet("ABS: Bloomberg/dealer consensus pricing")
            pdf.body("Pricing exceptions are reviewed daily by the middle office. Stale prices (unchanged >5 days) trigger independent verification. Material pricing adjustments require CCO approval.")
        elif i == 14:
            pdf.section("23. Distribution History")
            pdf.body("The fund has paid monthly distributions continuously since inception (November 2000):")
            pdf.table_row("FY2025 Distribution", "4.32 cents per unit")
            pdf.table_row("FY2024 Distribution", "4.15 cents per unit")
            pdf.table_row("FY2023 Distribution", "3.68 cents per unit")
            pdf.body("Monthly distributions provide a steady income stream for investors. Distribution amounts vary with prevailing interest rates and credit spreads.")
        elif i == 15:
            pdf.section("24. Key Person Clause")
            pdf.body("The PDS identifies the Head of Australian Fixed Income as the key person for this fund. In the event of their departure, Macquarie undertakes to notify investors within 10 business days and provide details of transitional arrangements.")
            pdf.body("Mitigation: The team of 10 professionals with average tenure of 11 years provides depth beyond any single individual. The two Senior PMs each have full authority to manage the fund independently.")
        elif i == 16:
            pdf.section("25. Minimum Investment")
            pdf.table_row("Minimum Initial Investment", "AUD 5,000")
            pdf.table_row("Minimum Additional", "AUD 1,000")
            pdf.table_row("Minimum Balance", "AUD 5,000")
            pdf.body("The minimum investment has been set to balance accessibility for retail investors with administrative efficiency.")
        else:
            pdf.section("26. Contact Information")
            pdf.body("Macquarie Investment Management Client Services")
            pdf.body("Phone: 1800 814 523")
            pdf.body("Email: service@macquarie.com")
            pdf.body("Website: www.macquarie.com/investing")
            pdf.body("Address: 50 Martin Place, Sydney NSW 2000")

    pdf.save("pf_macq001_pds.pdf")


def gen_quarterly():
    pdf = DocPDF("Macquarie Income Fund - Q1 2026 Report")
    pdf.cover_page("Macquarie Income Fund", "Quarterly Investment Report\nQ1 2026 (January - March)", "April 2026", "Macquarie Investment Management Limited")

    pdf.add_page()
    pdf.section("Performance Summary")
    pdf.body("The Macquarie Income Fund returned +1.12% (after fees) for the quarter ended 31 March 2026, outperforming the Bloomberg AusBond Bank Bill Index return of +0.98% by 0.14%.")
    pdf.table_row("Fund Return (Q1 2026)", "+1.12% (after fees)")
    pdf.table_row("Benchmark (Bank Bill Index)", "+0.98%")
    pdf.table_row("Excess Return", "+0.14%")
    pdf.table_row("1 Year Return", "+4.85%")
    pdf.table_row("3 Year Return (p.a.)", "+4.21%")
    pdf.table_row("5 Year Return (p.a.)", "+3.12%")
    pdf.table_row("Since Inception (p.a.)", "+4.48%")
    pdf.table_row("Fund Volatility (3yr)", "0.35% p.a.")
    pdf.table_row("Sharpe Ratio (3yr)", "2.15")
    pdf.table_row("Max Drawdown (3yr)", "-0.18%")
    pdf.table_row("Running Yield", "4.92%")
    pdf.table_row("Modified Duration", "0.82 years")

    pdf.add_page()
    pdf.section("Performance Attribution")
    pdf.body("Quarterly excess return of +0.14% attributed as follows:")
    pdf.subsection("Credit Selection: +0.10%")
    pdf.table_row("Bank Senior Bonds", "+0.04% (tightening spreads)")
    pdf.table_row("Corporate Bonds (BBB)", "+0.05% (carry and roll)")
    pdf.table_row("ABS/RMBS", "+0.01%")
    pdf.subsection("Duration/Yield Curve: +0.03%")
    pdf.body("Modest positive contribution from slightly long duration positioning ahead of expected rate cuts. Yield curve flattener contributed positively as the 2-3 year sector outperformed bills.")
    pdf.subsection("Other: +0.01%")
    pdf.body("Minor contribution from cash management and settlement timing.")
    pdf.body("Attribution is calculated internally and verified by the independent risk function. No third-party attribution audit is conducted given the simplicity of the strategy.")
    pdf.body("Tracking error for the quarter: 0.28% (annualised), within the target of <0.5%.")

    pdf.add_page()
    pdf.section("Portfolio Positioning")
    pdf.subsection("Current Allocation (31 March 2026)")
    pdf.table_row("Bank Deposits & CDs", "32%")
    pdf.table_row("Bank Senior Bonds", "24%")
    pdf.table_row("Corporate Bonds (A/BBB)", "22%")
    pdf.table_row("Government/Semi-Govt", "12%")
    pdf.table_row("Asset-Backed Securities", "8%")
    pdf.table_row("Cash", "2%")
    pdf.subsection("Credit Quality")
    pdf.table_row("AAA/AA", "48%")
    pdf.table_row("A", "31%")
    pdf.table_row("BBB", "19%")
    pdf.table_row("Below IG", "0%")
    pdf.table_row("Unrated", "2% (bank deposits)")
    pdf.subsection("Key Metrics")
    pdf.table_row("Modified Duration", "0.82 years")
    pdf.table_row("Weighted Avg Maturity", "1.4 years")
    pdf.table_row("Number of Holdings", "124")
    pdf.table_row("Largest Single Issuer", "4.2% (Commonwealth of Australia)")

    pdf.add_page()
    pdf.section("Market Commentary")
    pdf.body("Q1 2026 saw stable short-term rates as the RBA maintained the cash rate at 3.85%. Market expectations for rate cuts shifted from Q1 to H2 2026, causing modest flattening in the 1-3 year part of the curve.")
    pdf.body("Credit spreads compressed further during the quarter. Australian investment-grade spreads tightened 5-10 basis points, driven by strong demand from institutional investors seeking quality income and limited new supply. The tightening benefited the fund's overweight position in bank and corporate bonds.")
    pdf.body("No credit events affected the portfolio during the quarter. All holdings maintained investment-grade ratings.")

    pdf.add_page()
    pdf.section("Benchmark Comparison")
    pdf.body("The fund's outperformance of 0.14% for the quarter and 0.64% for the trailing 12 months continues the long-term track record of exceeding the Bloomberg AusBond Bank Bill Index.")
    pdf.body("The benchmark remains highly appropriate: the fund's portfolio duration (0.82 years) is close to the benchmark duration (~0.2 years), with the differential reflecting the modest duration extension permitted by the mandate to enhance returns.")
    pdf.body("The Bloomberg AusBond Bank Bill Index has been the fund's benchmark since inception (November 2000) with no changes. There are no plans to change the benchmark.")

    pdf.add_page()
    pdf.section("Risk Update")
    pdf.table_row("VaR (95%, 1-day)", "0.02% of NAV")
    pdf.table_row("Tracking Error (realised)", "0.28% p.a.")
    pdf.table_row("Credit Duration", "1.1 years")
    pdf.table_row("Spread Duration", "0.9 years")
    pdf.body("All risk metrics remained well within permitted limits throughout the quarter. No limit breaches occurred.")
    pdf.body("Stress test results (Q1 update): Under a +100bp rate shock scenario, estimated fund impact is -0.82%. Under a credit spread widening of +100bp, estimated impact is -0.95%. Both within acceptable ranges given the fund's low-risk mandate.")

    pdf.add_page()
    pdf.section("Outlook")
    pdf.body("Portfolio positioning for Q2 2026:")
    pdf.bullet("Duration: Maintain slightly long positioning (0.8-0.9 years) ahead of potential H2 rate cuts")
    pdf.bullet("Credit: Continue to favour bank senior and A-rated corporates. Modest reduction in BBB exposure given tight spreads.")
    pdf.bullet("ABS: Maintain allocation to prime RMBS given attractive relative value")
    pdf.bullet("Liquidity: Maintain above-minimum liquidity buffer given uncertain macro environment")

    pdf.add_page()
    pdf.section("Fund Facts")
    pdf.table_row("Fund Size (31 March 2026)", "AUD 4,215 million")
    pdf.table_row("Unit Price (31 March 2026)", "$1.0024")
    pdf.table_row("Distribution (March)", "0.38 cpu")
    pdf.table_row("Number of Unitholders", "~12,400")
    pdf.body("Net flows for Q1 2026: +AUD 145 million (net inflows). The fund continues to attract institutional and retail investors seeking quality short-duration income.")

    pdf.save("pf_macq001_quarterly.pdf")


if __name__ == "__main__":
    print("Generating Macquarie Income Fund documents...")
    gen_pds()
    gen_quarterly()
    print("Done!")
