"""Generate source documents for pf_pendal001 -- Pendal Australian Equities."""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from pdf_helpers import DocPDF


def gen_pds():
    pdf = DocPDF("Pendal Australian Equities - PDS 2026")
    pdf.cover_page("Pendal Australian Equities Fund", "Product Disclosure Statement 2026", "1 January 2026", "Pendal Group Limited")

    pdf.add_page()
    pdf.section("1. About Pendal Group")
    pdf.body("Pendal Group Limited (ABN 28 126 385 822, AFSL 228504) is the responsible entity and investment manager of the Pendal Australian Equities Fund. Pendal is one of Australia's largest independent investment managers, with a heritage dating back to 1980 through the former BT Investment Management.")
    pdf.table_row("ABN", "28 126 385 822")
    pdf.table_row("AFSL", "228504")
    pdf.table_row("Founded", "1980 (as BT Investment Management)")
    pdf.table_row("Headquarters", "Sydney, NSW")
    pdf.table_row("Total AUM", "AUD 28.4 billion")
    pdf.table_row("Ownership", "Listed on ASX (ASX: PDL)")
    pdf.body("Pendal Group holds AFSL 228504 which is current and in good standing. There are no enforceable undertakings issued by ASIC against Pendal Group in relation to this fund. The firm operates a dedicated compliance function overseen by a Chief Compliance Officer with direct Board reporting.")
    pdf.body("Pendal was formed following the demerger of BT Investment Management from Westpac Banking Corporation in 2007, and rebranded to Pendal Group in 2018. The firm maintains full operational independence from its former parent.")

    pdf.add_page()
    pdf.section("2. Investment Philosophy & Process")
    pdf.body("The Pendal Australian Equities Fund employs an active, bottom-up, fundamental stock selection approach designed to outperform the S&P/ASX 300 Accumulation Index over rolling 3-year periods.")
    pdf.body("The investment philosophy is built on three core tenets:")
    pdf.bullet("Quality businesses with sustainable competitive advantages trade at premiums that are often justified by superior long-term compounding.")
    pdf.bullet("Market inefficiencies exist primarily at the individual stock level, and deep fundamental research is the most reliable way to exploit them.")
    pdf.bullet("Risk management begins at the stock level -- understanding what you own is the primary defence against permanent capital loss.")
    pdf.subsection("Alpha Sources")
    pdf.body("The fund generates alpha through: (1) proprietary fundamental research identifying undervalued quality companies, (2) contrarian positioning when market sentiment diverges from fundamental value, and (3) active engagement with company management to unlock value.")
    pdf.subsection("Process Evolution")
    pdf.body("The investment process was refined in 2021 to incorporate quantitative screening as a complement to traditional fundamental research. A proprietary 'Quality Momentum Scorecard' was introduced to prioritise the research pipeline, though all final investment decisions remain fundamentally driven. The process evolved from a pure bottom-up approach to include top-down thematic overlays in 2023, recognising that sector and macroeconomic trends increasingly influence individual stock outcomes.")
    pdf.subsection("Investment Decision Framework")
    pdf.body("Stock selection follows a structured process: quantitative screening (universe of ~300 ASX stocks) -> fundamental research (detailed financial modelling, management meetings) -> portfolio construction (position sizing based on conviction and risk) -> ongoing monitoring. The average holding period is 2-3 years, reflecting the team's long-term orientation.")

    pdf.add_page()
    pdf.section("3. Portfolio Construction")
    pdf.body("The fund constructs a concentrated portfolio of 30-50 Australian equities selected from the S&P/ASX 300 universe.")
    pdf.subsection("Concentration Limits")
    pdf.table_row("Maximum single stock weight", "8% at cost, 10% at market")
    pdf.table_row("Maximum sector overweight", "+/- 10% vs benchmark")
    pdf.table_row("Maximum off-benchmark", "10% (stocks outside ASX 300)")
    pdf.table_row("Minimum number of holdings", "30")
    pdf.table_row("Maximum cash holding", "10%")
    pdf.table_row("Typical active share", "55-70%")
    pdf.body("Position sizing is determined by a combination of conviction level (1-5 scale from research team) and risk contribution. High-conviction ideas (level 4-5) are sized at 3-5% of portfolio. Lower-conviction holdings (level 2-3) are sized at 1-2%. All positions must have a positive expected return over 12-18 months.")
    pdf.body("Sector exposures are monitored daily relative to the benchmark. Deviations exceeding +/-10% require Portfolio Manager approval and documentation of the investment thesis supporting the overweight/underweight.")

    pdf.add_page()
    pdf.section("4. Benchmark & Objectives")
    pdf.table_row("Benchmark", "S&P/ASX 300 Accumulation Index")
    pdf.table_row("Objective", "Outperform benchmark by 3% p.a. (gross)")
    pdf.table_row("Tracking Error Target", "3-6% p.a.")
    pdf.table_row("Time Horizon", "Rolling 3-year periods")
    pdf.body("The S&P/ASX 300 Accumulation Index was selected as the benchmark because it represents the broadest investable universe of Australian equities, encompassing large-cap, mid-cap, and small-cap stocks. This benchmark has been used since the fund's inception in April 1997 and has not been changed.")
    pdf.body("The benchmark is considered appropriate because: (1) it matches the fund's investable universe (ASX-listed equities), (2) it includes dividend reinvestment consistent with the fund's total return objective, and (3) it is widely recognised and used by peers, enabling fair comparison.")

    pdf.add_page()
    pdf.section("5. Key Personnel")
    pdf.subsection("Crispin Murray -- Head of Equities & Lead Portfolio Manager")
    pdf.body("Crispin Murray has led Pendal's Australian equities team since 2010. He has over 28 years of investment experience, having previously served as Senior Portfolio Manager at BT Investment Management. Crispin holds a Bachelor of Commerce from the University of Melbourne and is a CFA charterholder.")
    pdf.subsection("Investment Team")
    pdf.body("The Australian Equities team comprises 12 investment professionals:")
    pdf.bullet("2 senior portfolio managers (Crispin Murray, deputy PM with 20 years exp)")
    pdf.bullet("6 sector research analysts (covering all GICS sectors)")
    pdf.bullet("2 quantitative analysts")
    pdf.bullet("1 ESG integration specialist")
    pdf.bullet("1 portfolio implementation manager")
    pdf.table_row("Average team tenure", "9.5 years")
    pdf.table_row("Average experience", "16 years")
    pdf.body("Key person risk: The PDS discloses Crispin Murray as a key person for this fund. A deputy portfolio manager with 20 years experience is designated as acting lead PM in the event of Crispin's absence. All research coverage has backup analysts assigned. The investment process is documented to ensure continuity.")

    pdf.add_page()
    pdf.section("6. ESG Integration")
    pdf.body("Pendal Group is a signatory to the UNPRI (since 2009) and received an A rating for Listed Equity incorporation in its most recent assessment.")
    pdf.bullet("ESG integration: ESG factors are incorporated into fundamental research for all stocks via a proprietary ESG scorecard. Material ESG risks can reduce position sizes or result in exclusion.")
    pdf.bullet("Exclusions: Controversial weapons, tobacco manufacturing (>5% revenue)")
    pdf.bullet("Active ownership: Pendal voted on 100% of proxy resolutions in FY2025. Voted against management on 18% of resolutions.")
    pdf.bullet("Engagement: Direct engagement with 45 ASX companies on material ESG topics in FY2025, focusing on climate disclosure, board diversity, and executive remuneration.")
    pdf.bullet("Climate: TCFD-aligned climate risk assessment conducted annually. Portfolio weighted average carbon intensity disclosed in quarterly reports.")

    pdf.add_page()
    pdf.section("7. Conflicts of Interest")
    pdf.body("Pendal Group maintains a Conflicts of Interest Policy reviewed annually by the Board:")
    pdf.bullet("Related parties: Pendal has no affiliated broker-dealer or custodian. All service providers are independent third parties selected via competitive tender.")
    pdf.bullet("Personal trading: All investment staff subject to pre-clearance, 30-day holding period, and prohibition on trading securities under active research coverage.")
    pdf.bullet("Soft dollars: Pendal does not accept soft dollar arrangements. Research is funded from the firm's own resources, not from brokerage commissions.")
    pdf.bullet("Board independence: The Pendal Group Board comprises 7 directors, 5 of whom are independent non-executive directors. The Chair is independent.")
    pdf.bullet("Cross-fund allocation: IPO and block trade allocations follow a documented fair allocation policy overseen by Compliance. Allocation reports are reviewed monthly.")

    pdf.add_page()
    pdf.section("8. Fees & Costs")
    pdf.table_row("Management Fee (MER)", "0.85% p.a. of NAV")
    pdf.table_row("Indirect Cost Ratio (ICR)", "0.02% p.a.")
    pdf.table_row("Performance Fee", "Nil")
    pdf.table_row("Buy Spread", "0.15%")
    pdf.table_row("Sell Spread", "0.15%")
    pdf.table_row("Entry/Exit Fees", "Nil")
    pdf.body("The Management Fee is accrued daily and paid monthly from fund assets. The ICR is minimal as the fund invests directly in ASX-listed securities rather than underlying funds.")
    pdf.body("Buy/sell spreads reflect the estimated transaction costs (brokerage + market impact) of investing/redeeming. Spreads are reviewed quarterly based on recent trading experience.")
    pdf.body("Total estimated cost to investors: 0.87% p.a. plus applicable buy/sell spread.")

    pdf.add_page()
    pdf.section("9. Business Viability")
    pdf.table_row("Fund AUM", "AUD 1,150 million")
    pdf.table_row("Fund Inception", "1 April 1997")
    pdf.table_row("APIR Code", "BTA0011AU")
    pdf.table_row("Firm Total AUM", "AUD 28.4 billion")
    pdf.table_row("3-Year AUM Growth (firm)", "+2.8% CAGR")
    pdf.table_row("Staff Turnover", "14% (industry avg: 18%)")
    pdf.body("Pendal Group (ASX: PDL) is a publicly listed, independent investment manager. The firm's ownership structure provides transparency and alignment with investors. Following the acquisition of TSW (US equities specialist) in 2020, the firm has diversified its revenue base geographically.")
    pdf.body("The Australian Equities Fund has operated for over 28 years with stable AUM. At AUD 1.15 billion, the fund is well above the minimum viable scale. Revenue from management fees adequately supports the dedicated 12-person investment team.")

    # Pad to ~20 pages
    for i in range(10):
        pdf.add_page()
        if i == 0:
            pdf.section("10. Regulatory Information")
            pdf.body("Pendal Group Limited holds AFSL 228504, which authorises it to operate registered managed investment schemes and provide general financial product advice.")
            pdf.body("The fund is registered with ASIC as a managed investment scheme (ARSN 089 817 559).")
            pdf.bullet("AFSL is current and in good standing")
            pdf.bullet("No enforceable undertakings in past 5 years")
            pdf.bullet("No material regulatory actions or proceedings")
            pdf.bullet("Member of AFCA (membership number: 10876)")
        elif i == 1:
            pdf.section("11. Risk Disclosures")
            pdf.body("Key risks of investing in the Pendal Australian Equities Fund:")
            pdf.bullet("Market risk: Australian equity markets can be volatile. The fund's concentrated approach means returns may diverge significantly from the benchmark.")
            pdf.bullet("Stock-specific risk: With 30-50 holdings, individual stock events can materially impact performance.")
            pdf.bullet("Liquidity risk: Small-cap holdings may be less liquid. The fund limits off-benchmark (ex-ASX 300) holdings to 10%.")
            pdf.bullet("Manager risk: Active management may underperform passive alternatives.")
        elif i == 2:
            pdf.section("12. Taxation")
            pdf.body("The fund operates under the AMIT regime. Distributions are made annually in June, comprising dividends (including franking credits), realised capital gains, and other income. Investors receive an AMMA statement for tax reporting purposes.")
        elif i == 3:
            pdf.section("13. Withdrawals")
            pdf.body("Withdrawal requests are processed daily. Payment is typically within 3-5 business days. The responsible entity may suspend withdrawals for up to 90 days in extraordinary circumstances (e.g., extreme market disruption preventing fair asset valuation).")
        elif i == 4:
            pdf.section("14. Governance")
            pdf.body("The fund's governance structure includes:")
            pdf.bullet("Board of Directors (7 members, 5 independent)")
            pdf.bullet("Investment Committee (4 members, chaired by Head of Equities)")
            pdf.bullet("Risk & Compliance Committee (3 independent directors)")
            pdf.bullet("Independent custodian (JP Morgan Chase Bank N.A.)")
            pdf.bullet("External auditor (Deloitte Touche Tohmatsu)")
        elif i == 5:
            pdf.section("15. Compliance Framework")
            pdf.body("Pendal's compliance program includes:")
            pdf.bullet("Annual compliance plan approved by the Board")
            pdf.bullet("Automated pre-trade and post-trade compliance monitoring")
            pdf.bullet("Monthly compliance reporting to the Board")
            pdf.bullet("Quarterly regulatory horizon scanning")
            pdf.bullet("Annual compliance training for all staff (100% completion)")
            pdf.body("Breach register: 2 minor breaches in past 3 years (both self-identified, no client impact, rectified within 24 hours). No significant breaches reported to ASIC.")
        elif i == 6:
            pdf.section("16. Additional Disclosures")
            pdf.body("Unit pricing: Units are priced daily based on closing ASX prices. The unit pricing policy has been audited by Deloitte.")
            pdf.body("Related party investments: The fund does not invest in any Pendal-managed sub-funds.")
            pdf.body("Derivatives: The fund may use exchange-traded index futures for cash equitisation purposes only (max 5% of NAV). No OTC derivatives are used.")
        elif i == 7:
            pdf.section("17. Distribution Policy")
            pdf.body("The fund distributes income annually in June. Distributions comprise dividends received (including franking credits), interest, and net realised capital gains. The fund aims to distribute 100% of taxable income each year.")
        elif i == 8:
            pdf.section("18. Valuation")
            pdf.body("All listed securities are valued at last traded ASX price at 4:00pm AEST. Cash and accruals are included at face value. Any unlisted holdings (rare) are valued by independent valuers at least annually. The valuation policy is reviewed annually by the Board and audited by Deloitte.")
        else:
            pdf.section("19. Contact & Glossary")
            pdf.body("Pendal Group Client Services: 1300 346 821")
            pdf.body("Email: client.services@pendalgroup.com")
            pdf.body("Website: www.pendalgroup.com")
            pdf.ln(5)
            pdf.body("AFSL: Australian Financial Services Licence")
            pdf.body("ASX: Australian Securities Exchange")
            pdf.body("GICS: Global Industry Classification Standard")
            pdf.body("ICR: Indirect Cost Ratio")
            pdf.body("MER: Management Expense Ratio")

    pdf.save("pf_pendal001_pds.pdf")


def gen_quarterly():
    pdf = DocPDF("Pendal Australian Equities - Q1 2026 Performance Report")
    pdf.cover_page("Pendal Australian Equities Fund", "Quarterly Performance Report\nQ1 2026 (January - March)", "April 2026", "Pendal Group Limited")

    pdf.add_page()
    pdf.section("Performance Summary")
    pdf.body("The Pendal Australian Equities Fund returned +4.8% (after fees) for the quarter ended 31 March 2026, outperforming the S&P/ASX 300 Accumulation Index return of +3.5% by 1.3%.")
    pdf.table_row("Fund Return (Q1 2026)", "+4.8% (after fees)")
    pdf.table_row("Benchmark (S&P/ASX 300 AI)", "+3.5%")
    pdf.table_row("Excess Return", "+1.3%")
    pdf.table_row("1 Year Return", "+14.2%")
    pdf.table_row("3 Year Return (p.a.)", "+10.8%")
    pdf.table_row("5 Year Return (p.a.)", "+9.5%")
    pdf.table_row("Since Inception (p.a.)", "+10.1%")
    pdf.table_row("Tracking Error (3yr)", "4.8% p.a.")
    pdf.table_row("Information Ratio (3yr)", "0.85")
    pdf.table_row("Sharpe Ratio (3yr)", "0.72")
    pdf.table_row("Maximum Drawdown (3yr)", "-14.8%")
    pdf.table_row("Active Share", "62%")

    pdf.add_page()
    pdf.section("Performance Attribution -- Brinson Analysis")
    pdf.body("Quarterly excess return of +1.3% decomposed:")
    pdf.subsection("Sector Allocation Effect: +0.42%")
    pdf.table_row("Financials (overweight)", "+0.22%")
    pdf.table_row("Materials (underweight)", "+0.15%")
    pdf.table_row("Technology (overweight)", "+0.12%")
    pdf.table_row("Consumer Staples (underweight)", "-0.07%")
    pdf.subsection("Stock Selection Effect: +0.95%")
    pdf.table_row("Financials", "+0.35% (CBA, Macquarie)")
    pdf.table_row("Health Care", "+0.28% (CSL, Cochlear)")
    pdf.table_row("Technology", "+0.22% (Xero, WiseTech)")
    pdf.table_row("Materials", "+0.10%")
    pdf.subsection("Interaction Effect: -0.07%")
    pdf.body("Factor decomposition: Quality (+0.45%), Momentum (+0.38%), Value (+0.22%), Size (-0.15%), Residual (+0.40%).")
    pdf.body("Performance attribution is calculated using a Brinson-Fachler model and verified by the independent risk function. All returns are after transaction costs.")

    pdf.add_page()
    pdf.section("Portfolio Positioning")
    pdf.body("Top 10 Holdings (as at 31 March 2026):")
    pdf.table_row("1. BHP Group", "7.2% (benchmark: 9.5%)")
    pdf.table_row("2. Commonwealth Bank", "6.8% (benchmark: 7.2%)")
    pdf.table_row("3. CSL Limited", "6.5% (benchmark: 5.8%)")
    pdf.table_row("4. Macquarie Group", "5.1% (benchmark: 3.2%)")
    pdf.table_row("5. Wesfarmers", "4.2% (benchmark: 3.5%)")
    pdf.table_row("6. Xero Limited", "3.8% (benchmark: 1.5%)")
    pdf.table_row("7. Woodside Energy", "3.5% (benchmark: 3.8%)")
    pdf.table_row("8. ANZ Banking Group", "3.2% (benchmark: 3.1%)")
    pdf.table_row("9. Goodman Group", "3.0% (benchmark: 2.8%)")
    pdf.table_row("10. Cochlear", "2.8% (benchmark: 1.2%)")
    pdf.body("Number of holdings: 38 (down from 41 at Dec-25). Cash: 2.1%.")

    pdf.add_page()
    pdf.section("Market Commentary")
    pdf.body("The S&P/ASX 300 Accumulation Index rose 3.5% in Q1 2026. Financials led (+5.8%) driven by bank earnings upgrades and wealth management recovery. Materials were mixed (+2.1%) with iron ore softening offset by gold strength. Technology outperformed (+7.2%) on continued AI capex themes.")
    pdf.body("The fund benefited from overweight positions in quality growth names (CSL, Xero, Cochlear) and financial sector stock selection (Macquarie). Underperformance came from an underweight in resources, partially offset by individual stock selection within the sector.")

    pdf.add_page()
    pdf.section("Benchmark Comparison")
    pdf.body("Tracking error over the quarter was 4.8% annualised, within the target range of 3-6%. The fund's beta to the S&P/ASX 300 was 0.95, reflecting the active but benchmark-aware approach.")
    pdf.body("The benchmark remains appropriate for this fund as the portfolio is invested exclusively in ASX-listed equities, predominantly within the ASX 300 universe (92% by weight). No benchmark change has occurred or is planned.")
    pdf.body("Carbon intensity: Portfolio WACI of 142 tCO2e/$M revenue vs benchmark 185 tCO2e/$M (-23% underweight).")

    pdf.save("pf_pendal001_quarterly.pdf")


def gen_ddq():
    pdf = DocPDF("Pendal Australian Equities - DDQ Response")
    pdf.cover_page("Pendal Group Limited", "Manager Due Diligence Questionnaire Response\nPendal Australian Equities Fund", "March 2026", "Pendal Group Limited")

    pdf.add_page()
    pdf.section("1. Risk Management Framework")
    pdf.body("Pendal Group operates a risk management framework aligned with ISO 31000 principles:")
    pdf.subsection("Risk Governance")
    pdf.bullet("Board Risk Committee: 3 independent directors, meets quarterly")
    pdf.bullet("Investment Risk Committee: CIO, Head of Risk, Lead PMs -- meets monthly")
    pdf.bullet("Independent Risk team: 6 professionals reporting to CRO (not CIO)")
    pdf.subsection("Quantitative Risk Limits")
    pdf.table_row("Tracking Error", "Hard limit: 8% p.a. (target: 3-6%)")
    pdf.table_row("Single Stock Active Bet", "Max +/- 5% vs benchmark")
    pdf.table_row("Sector Active Bet", "Max +/- 10% vs benchmark")
    pdf.table_row("Beta Range", "0.8 - 1.2")
    pdf.table_row("Cash Limit", "Max 10%")
    pdf.body("Drawdown triggers: A drawdown exceeding -10% from peak (rolling 12 months) triggers a formal review by the Investment Risk Committee. A drawdown exceeding -15% triggers Board notification and a portfolio de-risking review.")
    pdf.body("Escalation: Limit breaches are reported to CRO within 2 hours. The PM has 3 business days to rectify. Unrectified breaches are escalated to the Board Risk Committee.")

    pdf.add_page()
    pdf.section("2. Operational Infrastructure")
    pdf.subsection("Service Providers")
    pdf.table_row("Custodian", "JP Morgan Chase Bank N.A. (APRA-regulated)")
    pdf.table_row("Fund Administrator", "JP Morgan (unit pricing, accounting)")
    pdf.table_row("Registry", "Link Market Services")
    pdf.table_row("External Auditor", "Deloitte Touche Tohmatsu")
    pdf.subsection("Technology Systems")
    pdf.table_row("OMS", "Charles River IMS")
    pdf.table_row("PMS", "FactSet")
    pdf.table_row("Risk System", "FactSet Multi-Asset Class (MAC)")
    pdf.table_row("Compliance", "Charles River Compliance (automated)")
    pdf.table_row("Reconciliation", "IntelliMatch (daily automated)")
    pdf.subsection("Audit & Controls")
    pdf.body("Most recent external audit (30 June 2025): Unqualified opinion by Deloitte. No material findings.")
    pdf.body("GS007 assurance report obtained annually from JP Morgan covering custody and administration. Most recent (December 2025): No exceptions noted.")
    pdf.body("Internal audit function conducts annual reviews of key operational processes. Most recent cycle covered trade execution, reconciliation, and unit pricing (all satisfactory).")

    pdf.add_page()
    pdf.section("3. Key Person Risk & Team")
    pdf.body("Crispin Murray is identified as the key person for this fund. Mitigation measures:")
    pdf.bullet("Formal succession plan: Deputy PM (20 years experience) designated as acting lead in Crispin's absence")
    pdf.bullet("Team-based research: All investment ideas generated by team; no single-analyst reliance")
    pdf.bullet("Documented process: Investment framework and research templates ensure process continuity")
    pdf.bullet("Non-compete: Key personnel subject to 12-month non-compete clauses")
    pdf.subsection("Team Stability")
    pdf.table_row("Crispin Murray tenure", "16 years (at Pendal/BTIM)")
    pdf.table_row("Deputy PM tenure", "12 years")
    pdf.table_row("Average analyst tenure", "7.5 years")
    pdf.table_row("Team turnover (3yr avg)", "10%")
    pdf.body("No senior departures in the past 3 years. The team has been stable since 2021.")

    pdf.add_page()
    pdf.section("4. Business Continuity & DR")
    pdf.table_row("RTO (critical systems)", "2 hours")
    pdf.table_row("RPO", "30 minutes (near-real-time replication)")
    pdf.table_row("DR Site", "Macquarie Park, Sydney (hot standby)")
    pdf.table_row("Remote Trading", "All PMs can trade from home (Bloomberg Terminal)")
    pdf.subsection("Testing")
    pdf.body("Full BCP/DR test conducted semi-annually. Most recent test (October 2025): Successfully executed full trading day from DR site. All systems operational within 1.5 hours (within RTO of 2 hours).")
    pdf.body("COVID-era validation: Team operated remotely March 2020 - December 2021 with zero trading disruptions. This experience led to permanent investment in remote infrastructure.")
    pdf.body("BCP reviewed annually by the Board. Last update: August 2025.")

    pdf.add_page()
    pdf.section("5. Compliance & Regulatory")
    pdf.body("AFSL 228504 is current with no conditions or restrictions beyond standard authorisations.")
    pdf.bullet("Compliance team: 8 professionals, CCO reports to Board")
    pdf.bullet("Annual compliance plan (last approved: January 2026)")
    pdf.bullet("Automated pre/post-trade compliance monitoring via Charles River")
    pdf.bullet("Breach register: 2 minor breaches in past 3 years (both operational, self-identified, no client impact)")
    pdf.bullet("No ASIC enforceable undertakings or regulatory actions in past 10 years")
    pdf.bullet("AFCA member (number: 10876)")
    pdf.body("Regulatory reporting: All ASIC and APRA reporting obligations met on time. Regular ASIC surveillance visits received (last: March 2025, no adverse findings).")

    pdf.add_page()
    pdf.section("6. Conflicts of Interest")
    pdf.subsection("Related Party Transactions")
    pdf.body("Pendal has no affiliated broker-dealer, custodian, or administrator. All service providers are independent. The fund does not invest in Pendal-managed sub-funds.")
    pdf.subsection("Personal Trading")
    pdf.bullet("Pre-clearance required for all trades by investment staff")
    pdf.bullet("30-day minimum holding period")
    pdf.bullet("Securities under active coverage: trading prohibited")
    pdf.bullet("Quarterly certification and annual disclosure")
    pdf.bullet("Compliance monitoring via automated system")
    pdf.subsection("Trade Allocation")
    pdf.body("Fair allocation policy ensures equitable distribution of IPOs, block trades, and limited opportunities across all Pendal funds. Allocations are documented and reviewed monthly by Compliance. Pro-rata allocation is the default; deviations require documented justification and CCO approval.")
    pdf.subsection("Soft Dollars")
    pdf.body("Pendal does not accept soft dollar commissions. All external research is paid for from the firm's P&L. Brokerage is allocated solely on best execution criteria.")

    pdf.add_page()
    pdf.section("7. Business Viability")
    pdf.table_row("Pendal Group Revenue (FY2025)", "AUD 312 million")
    pdf.table_row("Net Profit (FY2025)", "AUD 67 million")
    pdf.table_row("Total AUM (Dec 2025)", "AUD 28.4 billion")
    pdf.table_row("3-Year AUM CAGR", "+2.8%")
    pdf.table_row("Dividend Payout", "70% of earnings")
    pdf.subsection("AUM Trend")
    pdf.table_row("Dec 2023", "AUD 26.1 billion")
    pdf.table_row("Dec 2024", "AUD 27.2 billion")
    pdf.table_row("Dec 2025", "AUD 28.4 billion")
    pdf.subsection("Staff & Retention")
    pdf.table_row("Total employees", "285")
    pdf.table_row("Investment professionals", "62")
    pdf.table_row("Voluntary turnover (2025)", "14%")
    pdf.table_row("Average tenure (investment)", "9.2 years")
    pdf.body("Pendal is well-capitalised with no debt and maintains regulatory capital well above ASIC requirements. The firm's diversified asset class coverage and international expansion provide revenue stability. No wind-down indicators are present.")

    # Pad to ~14 pages
    for i in range(6):
        pdf.add_page()
        if i == 0:
            pdf.section("8. Technology & Cyber Security")
            pdf.body("Pendal's technology framework:")
            pdf.bullet("ISO 27001 certified ISMS")
            pdf.bullet("Annual penetration testing (CrowdStrike, last: September 2025, no critical findings)")
            pdf.bullet("SOC 2 Type II report on internal technology controls")
            pdf.bullet("MFA on all systems, privileged access management")
            pdf.bullet("24/7 security monitoring via managed SOC")
            pdf.bullet("Monthly phishing simulations (click rate <3%)")
        elif i == 1:
            pdf.section("9. Proxy Voting & Stewardship")
            pdf.body("Pendal exercises voting rights on all equity holdings:")
            pdf.table_row("Resolutions voted (FY2025)", "100% of eligible")
            pdf.table_row("Votes against management", "18%")
            pdf.table_row("Companies engaged", "45")
            pdf.body("Key engagement themes: climate disclosure, board diversity, executive remuneration alignment, modern slavery supply chain.")
            pdf.body("Voting records are published quarterly on the Pendal website.")
        elif i == 2:
            pdf.section("10. Liquidity Management")
            pdf.body("The fund invests primarily in ASX 300 stocks with high liquidity:")
            pdf.bullet("92% of portfolio in ASX 300 stocks (typically 5+ day liquidity)")
            pdf.bullet("8% in smaller companies with adequate but lower liquidity")
            pdf.bullet("No unlisted or illiquid investments")
            pdf.bullet("Liquidity stress testing conducted quarterly")
            pdf.bullet("Large redemption protocol: redemptions >5% of fund trigger PM notification")
        elif i == 3:
            pdf.section("11. Counterparty Risk")
            pdf.body("Minimal counterparty risk given the fund's direct equity investment approach:")
            pdf.bullet("No OTC derivatives")
            pdf.bullet("Exchange-traded futures (if used) cleared via ASX Clear")
            pdf.bullet("Custodian credit risk managed through APRA regulation of JP Morgan")
            pdf.bullet("Securities lending: Not conducted")
        elif i == 4:
            pdf.section("12. Insurance")
            pdf.body("Pendal maintains comprehensive insurance coverage:")
            pdf.bullet("Professional Indemnity: AUD 100 million (Lloyds of London)")
            pdf.bullet("Directors & Officers: AUD 50 million")
            pdf.bullet("Crime/Fidelity: AUD 30 million")
            pdf.bullet("Cyber Insurance: AUD 20 million")
        else:
            pdf.section("13. Appendix")
            pdf.body("Organisation Structure:")
            pdf.body("Board of Directors -> CEO -> CIO (Equities, Fixed Income, Multi-Asset)")
            pdf.body("Crispin Murray reports to: CIO")
            pdf.body("Independent functions: CRO, CCO, Internal Audit -- all report to Board")

    pdf.save("pf_pendal001_ddq.pdf")


if __name__ == "__main__":
    print("Generating Pendal Australian Equities documents...")
    gen_pds()
    gen_quarterly()
    gen_ddq()
    print("Done!")
