"""Generate source documents for pf_amp001 — AMP Growth Fund."""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from pdf_helpers import DocPDF


def gen_pds():
    pdf = DocPDF("AMP Growth Fund - PDS 2026")
    pdf.cover_page("AMP Growth Fund", "Product Disclosure Statement 2026", "1 January 2026", "AMP Capital Investors Limited")

    pdf.add_page()
    pdf.section("1. About AMP Capital Investors")
    pdf.body("AMP Capital Investors Limited (ABN 59 001 777 591, AFSL 232030) is the responsible entity and investment manager of the AMP Growth Fund. AMP Capital has been managing investments since 1849, making it one of Australia's oldest and most established investment managers.")
    pdf.body("AMP Capital is a wholly-owned subsidiary of AMP Limited (ASX: AMP), listed on the Australian Securities Exchange. The firm manages approximately AUD 58.2 billion in assets under management across diversified, fixed income, infrastructure, and real estate strategies.")
    pdf.table_row("ABN", "59 001 777 591")
    pdf.table_row("AFSL", "232030")
    pdf.table_row("Founded", "1849")
    pdf.table_row("Headquarters", "Sydney, NSW")
    pdf.table_row("Total AUM", "AUD 58.2 billion")
    pdf.table_row("Ownership", "Wholly-owned subsidiary of AMP Limited (ASX: AMP)")
    pdf.body("AMP Capital has maintained its AFSL continuously since the licensing regime was introduced. There have been no enforceable undertakings issued by ASIC against AMP Capital Investors Limited in respect of the AMP Growth Fund in the past five years. The firm's compliance framework is overseen by a dedicated Chief Compliance Officer reporting directly to the Board.")

    pdf.add_page()
    pdf.section("2. Investment Philosophy & Process")
    pdf.body("The AMP Growth Fund employs a dynamic asset allocation approach designed to deliver returns in excess of CPI + 4.5% per annum over rolling 5-year periods. The fund's investment philosophy is grounded in three core beliefs:")
    pdf.bullet("Markets are not perfectly efficient, and disciplined active management can exploit mispricings across asset classes.")
    pdf.bullet("Diversification across asset classes, geographies, and investment styles reduces portfolio risk without proportionally reducing expected returns.")
    pdf.bullet("Dynamic asset allocation, informed by fundamental valuation and macroeconomic analysis, adds value over static benchmark weights.")
    pdf.body("The investment process has evolved since the fund's inception in 1998. Initially a balanced fund with fixed strategic weights, the approach shifted to dynamic asset allocation in 2008 following the GFC, recognising that valuation-driven tactical shifts could improve risk-adjusted outcomes. The current process, refined in 2019, incorporates quantitative signals alongside fundamental analysis.")
    pdf.subsection("Alpha Sources")
    pdf.body("The fund targets alpha from three primary sources: (1) strategic tilts between growth and defensive assets based on 12-month forward valuation models, (2) manager selection within each asset class using a proprietary scoring system, and (3) portfolio construction overlays including currency hedging and volatility management.")
    pdf.subsection("Process Evolution")
    pdf.body("The investment process underwent a significant evolution in 2019 with the introduction of machine-learning-based signals for tactical asset allocation. These signals complement, but do not replace, the fundamental views of the investment team. The integration was phased over 18 months with formal back-testing and governance approval at each stage.")

    pdf.add_page()
    pdf.section("3. Portfolio Construction")
    pdf.body("The AMP Growth Fund targets a growth-oriented asset allocation with the following strategic ranges:")
    pdf.table_row("Australian Equities", "20-40% (SAA: 30%)")
    pdf.table_row("International Equities", "20-40% (SAA: 30%)")
    pdf.table_row("Fixed Income", "5-25% (SAA: 15%)")
    pdf.table_row("Real Assets", "5-20% (SAA: 10%)")
    pdf.table_row("Alternatives", "0-15% (SAA: 10%)")
    pdf.table_row("Cash", "0-15% (SAA: 5%)")
    pdf.subsection("Concentration Limits")
    pdf.body("The fund applies the following concentration limits to manage risk:")
    pdf.bullet("Maximum single security exposure: 5% of portfolio at cost")
    pdf.bullet("Maximum single sector exposure: 30% of total equities allocation")
    pdf.bullet("Maximum single manager allocation: 20% of total fund")
    pdf.bullet("Maximum emerging markets exposure: 15% of total fund")
    pdf.bullet("Maximum illiquid assets: 20% of total fund")
    pdf.body("Rebalancing is conducted monthly to within +/-3% of strategic asset allocation targets. A hard deviation limit of +/-10% from SAA triggers mandatory rebalancing within 5 business days regardless of the regular cycle.")

    pdf.add_page()
    pdf.section("4. Benchmark & Objectives")
    pdf.body("The fund's investment objective is to deliver total returns (income and capital growth) exceeding CPI + 4.5% per annum after fees over rolling 5-year periods.")
    pdf.table_row("Primary Benchmark", "CPI + 4.5% p.a.")
    pdf.table_row("Peer Benchmark", "Morningstar Multi-Sector Growth Category")
    pdf.table_row("Risk Objective", "Probability of negative return < 1 in 5 years")
    pdf.body("The CPI + 4.5% benchmark was selected as it represents a real return target appropriate for a growth-oriented investor with a 5+ year time horizon. This benchmark has been in use since fund inception in 1998 and has not been changed.")
    pdf.body("The benchmark is considered appropriate because: (1) it reflects the absolute-return objective of the fund rather than tying performance to volatile market indices, (2) it incorporates inflation protection for real purchasing power, and (3) the 4.5% real return premium is consistent with long-term equity risk premiums in Australian and global markets.")

    pdf.add_page()
    pdf.section("5. Key Personnel")
    pdf.body("The AMP Growth Fund is managed by the Multi-Asset Group within AMP Capital, led by:")
    pdf.subsection("Anna Shelley — Chief Investment Officer")
    pdf.body("Anna Shelley has served as CIO of AMP Capital since 2020. She has over 25 years of investment experience, having previously served as Deputy CIO and Head of Investment Strategy. Anna holds a Master of Applied Finance from Macquarie University and is a CFA charterholder.")
    pdf.subsection("Investment Team")
    pdf.body("The Multi-Asset Group comprises 18 investment professionals with an average tenure of 8.2 years. The team includes:")
    pdf.bullet("4 senior portfolio managers (average experience: 18 years)")
    pdf.bullet("6 asset allocation analysts")
    pdf.bullet("4 manager research analysts")
    pdf.bullet("2 quantitative strategists")
    pdf.bullet("2 portfolio implementation specialists")
    pdf.body("Key person risk is mitigated through team-based decision making. No single individual has sole authority over asset allocation decisions. The Investment Committee (5 members) must approve all strategic and tactical shifts exceeding 3% of portfolio value.")
    pdf.body("Succession planning: The Deputy CIO is formally designated as acting CIO in the event of the CIO's absence. All portfolio managers have identified successors who participate in all investment decisions as part of ongoing development.")

    pdf.add_page()
    pdf.section("6. ESG Integration")
    pdf.body("AMP Capital is a signatory to the United Nations Principles for Responsible Investment (UNPRI) since 2007. The firm received an A+ rating for Strategy & Governance in its most recent UNPRI assessment.")
    pdf.body("ESG integration in the AMP Growth Fund is implemented through:")
    pdf.bullet("Negative screening: Exclusion of controversial weapons manufacturers, tobacco producers (>10% revenue), and thermal coal miners (>30% revenue)")
    pdf.bullet("ESG integration in manager selection: All underlying managers are assessed on ESG capabilities as part of the due diligence process")
    pdf.bullet("Active ownership: AMP Capital exercises voting rights across all equity holdings and engages with companies on material ESG issues")
    pdf.bullet("Climate risk: Portfolio carbon footprint is measured and disclosed annually; a Net Zero 2050 pathway has been adopted")
    pdf.body("The firm's Responsible Investment Policy is reviewed annually by the Board and is publicly available on the AMP Capital website.")

    pdf.add_page()
    pdf.section("7. Conflicts of Interest")
    pdf.body("AMP Capital maintains a comprehensive Conflicts of Interest Policy, approved by the Board and reviewed annually. Key provisions include:")
    pdf.bullet("Related party transactions: All transactions with AMP Group entities are conducted at arm's length and require independent director approval. The fund may invest in AMP-managed sub-funds subject to fee rebate arrangements that eliminate double-charging.")
    pdf.bullet("Personal trading: All investment staff must pre-clear personal securities trades through an automated compliance system. A 30-day minimum holding period applies. Trading in securities on the fund's active buy/sell list is prohibited.")
    pdf.bullet("Soft dollar arrangements: AMP Capital does not accept soft dollar commissions. All brokerage is allocated solely on the basis of best execution for unitholders.")
    pdf.bullet("Board independence: The Responsible Entity board has a majority of independent directors (4 of 6). The Chair is an independent non-executive director.")
    pdf.body("A register of conflicts is maintained by the Compliance team and reported to the Board quarterly.")

    pdf.add_page()
    pdf.section("8. Fees & Costs")
    pdf.body("The following fees apply to the AMP Growth Fund:")
    pdf.table_row("Management Fee (MER)", "0.67% p.a. of NAV")
    pdf.table_row("Indirect Cost Ratio (ICR)", "0.12% p.a.")
    pdf.table_row("Buy Spread", "0.10%")
    pdf.table_row("Sell Spread", "0.10%")
    pdf.table_row("Performance Fee", "Nil")
    pdf.table_row("Entry/Exit Fees", "Nil")
    pdf.body("The Management Fee is calculated daily on the net asset value of the fund and deducted monthly. The ICR represents estimated costs incurred by underlying managers and is deducted from the fund's assets.")
    pdf.body("The buy/sell spread compensates existing investors for transaction costs incurred when new investors enter or existing investors redeem. Spreads are reviewed quarterly and adjusted based on actual transaction costs.")
    pdf.body("Total estimated costs to investors (all-in): 0.79% p.a. plus applicable buy/sell spread on entry/exit.")

    pdf.add_page()
    pdf.section("9. Business Viability")
    pdf.body("AMP Capital Investors manages AUD 58.2 billion across all strategies as at 31 December 2025. The firm is a wholly-owned subsidiary of AMP Limited (ASX: AMP), a publicly listed financial services company.")
    pdf.table_row("Fund AUM", "AUD 2,840 million")
    pdf.table_row("Fund Inception", "1 July 1998")
    pdf.table_row("3-Year AUM Growth", "+4.2% CAGR")
    pdf.table_row("Staff Turnover", "12% (industry avg: 18%)")
    pdf.body("The AMP Growth Fund has operated continuously for over 27 years. Despite broader industry consolidation affecting AMP Limited, the fund management business has maintained stable AUM and team retention. The parent company's restructuring in 2022-23 resulted in a clearer focus on the investment management division.")
    pdf.body("There are no current indicators of wind-down risk. The fund's AUM of AUD 2.84 billion is well above the economic viability threshold, and the management fee revenue adequately supports the investment team.")

    # Pad to ~24 pages
    for i in range(13):
        pdf.add_page()
        if i == 0:
            pdf.section("10. Additional Disclosures")
            pdf.body("This section provides additional regulatory disclosures required under the Corporations Act 2001 and ASIC Regulatory Guide 97.")
        elif i == 1:
            pdf.subsection("Taxation")
            pdf.body("The fund is an Australian resident trust for tax purposes. Distributions are made semi-annually (June and December). The fund has elected into the Attribution Managed Investment Trust (AMIT) regime, providing investors with clear tax reporting via an AMMA statement.")
        elif i == 2:
            pdf.subsection("Withdrawal Rights")
            pdf.body("Investors may withdraw from the fund by submitting a withdrawal request on any business day. Withdrawals are typically processed within 5 business days. In extraordinary circumstances, the responsible entity may suspend withdrawals for up to 90 days under the fund's constitution.")
        elif i == 3:
            pdf.subsection("Unit Pricing Policy")
            pdf.body("Unit prices are calculated daily based on the net asset value of the fund divided by units on issue. Valuations of underlying assets follow the valuation policy reviewed by the fund's auditor. Listed securities are valued at last traded price; unlisted assets are valued by independent valuers at least annually.")
        elif i == 4:
            pdf.subsection("Complaints Resolution")
            pdf.body("Complaints can be directed to the AMP Capital Client Services team. If not resolved within 45 days, complaints may be escalated to the Australian Financial Complaints Authority (AFCA). AFCA membership number: 10523.")
        elif i == 5:
            pdf.section("11. Risk Disclosures")
            pdf.body("All investments carry risk. The significant risks of investing in the AMP Growth Fund include:")
            pdf.bullet("Market risk: The value of investments may fall due to adverse market conditions.")
            pdf.bullet("Currency risk: International investments are subject to exchange rate fluctuations. The fund hedges approximately 50% of foreign currency exposure.")
            pdf.bullet("Liquidity risk: Some assets (real estate, infrastructure) may be difficult to sell quickly at fair value.")
            pdf.bullet("Manager risk: The risk that underlying managers underperform their benchmarks or fail to manage assets prudently.")
            pdf.bullet("Regulatory risk: Changes to tax laws, superannuation rules, or financial regulations may adversely affect returns.")
        elif i == 6:
            pdf.subsection("Risk Metrics (Target)")
            pdf.body("The fund targets the following risk parameters:")
            pdf.table_row("Expected Volatility", "8-12% p.a.")
            pdf.table_row("Maximum Drawdown Target", "-20% (peak to trough)")
            pdf.table_row("Tracking Error vs SAA", "2-5% p.a.")
            pdf.table_row("Probability Negative Year", "< 1 in 5 years")
        elif i == 7:
            pdf.section("12. Governance Structure")
            pdf.body("The AMP Growth Fund's governance structure includes the following bodies:")
            pdf.bullet("Board of the Responsible Entity (6 directors, 4 independent)")
            pdf.bullet("Investment Committee (5 members, chaired by CIO)")
            pdf.bullet("Risk & Compliance Committee (3 independent directors)")
            pdf.bullet("Product Governance Committee")
        elif i == 8:
            pdf.subsection("Investment Decision Framework")
            pdf.body("Strategic asset allocation decisions require Investment Committee approval by majority vote. Tactical shifts within approved ranges may be implemented by the lead portfolio manager. Any deviation beyond approved ranges requires emergency IC approval within 24 hours.")
        elif i == 9:
            pdf.section("13. Regulatory Information")
            pdf.body("AMP Capital Investors Limited holds Australian Financial Services Licence number 232030, authorising it to operate registered managed investment schemes. The licence is current and in good standing as at the date of this PDS.")
            pdf.body("The fund is registered with ASIC as a managed investment scheme (ARSN 089 595 321). AMP Capital is a member of the Financial Services Council (FSC) and adheres to the FSC Standards.")
        elif i == 10:
            pdf.subsection("Compliance Framework")
            pdf.body("AMP Capital maintains a compliance framework that includes: a dedicated compliance team of 12 professionals, automated trade surveillance systems, monthly compliance reporting to the Board, annual compliance plan approved by the Board, and regular staff training on regulatory obligations.")
            pdf.body("The firm maintains a breach register as required under its AFSL conditions. All breaches are reported to the Board's Risk & Compliance Committee and, where required, to ASIC. There have been no significant breaches relating to the AMP Growth Fund in the past three years.")
        elif i == 11:
            pdf.section("14. Contact Information")
            pdf.body("AMP Capital Client Services")
            pdf.body("Phone: 1800 257 111")
            pdf.body("Email: clientservices@ampcapital.com")
            pdf.body("Website: www.ampcapital.com")
            pdf.body("Address: 33 Alfred Street, Sydney NSW 2000")
        else:
            pdf.section("15. Glossary")
            pdf.body("AFSL: Australian Financial Services Licence")
            pdf.body("ASIC: Australian Securities and Investments Commission")
            pdf.body("CPI: Consumer Price Index")
            pdf.body("ICR: Indirect Cost Ratio")
            pdf.body("MER: Management Expense Ratio")
            pdf.body("NAV: Net Asset Value")
            pdf.body("SAA: Strategic Asset Allocation")
            pdf.body("UNPRI: United Nations Principles for Responsible Investment")

    pdf.save("pf_amp001_pds.pdf")


def gen_quarterly():
    pdf = DocPDF("AMP Growth Fund - Q1 2026 Quarterly Report")
    pdf.cover_page("AMP Growth Fund", "Quarterly Investment Report\nQ1 2026 (January - March)", "April 2026", "AMP Capital Investors Limited")

    pdf.add_page()
    pdf.section("Performance Summary")
    pdf.body("The AMP Growth Fund returned +2.1% (after fees) for the quarter ended 31 March 2026, outperforming the CPI + 4.5% p.a. benchmark return of +1.6% for the quarter.")
    pdf.table_row("Fund Return (Q1 2026)", "+2.1% (after fees)")
    pdf.table_row("Benchmark Return (Q1)", "+1.6% (CPI + 4.5% p.a. / 4)")
    pdf.table_row("Excess Return", "+0.5%")
    pdf.table_row("1 Year Return", "+9.8%")
    pdf.table_row("3 Year Return (p.a.)", "+7.2%")
    pdf.table_row("5 Year Return (p.a.)", "+6.8%")
    pdf.table_row("Since Inception (p.a.)", "+7.5%")
    pdf.table_row("Fund Volatility (3yr)", "9.4% p.a.")
    pdf.table_row("Sharpe Ratio (3yr)", "0.62")
    pdf.table_row("Maximum Drawdown (3yr)", "-12.3%")
    pdf.table_row("Tracking Error", "3.2% p.a.")

    pdf.add_page()
    pdf.section("Performance Attribution — Brinson Analysis")
    pdf.body("The following attribution analysis decomposes the fund's quarterly excess return of +0.5% into asset allocation and selection effects:")
    pdf.subsection("Asset Allocation Effect: +0.32%")
    pdf.table_row("Australian Equities (overweight)", "+0.15%")
    pdf.table_row("International Equities (underweight)", "-0.08%")
    pdf.table_row("Fixed Income (underweight)", "+0.12%")
    pdf.table_row("Real Assets (overweight)", "+0.09%")
    pdf.table_row("Cash (underweight)", "+0.04%")
    pdf.subsection("Selection Effect: +0.22%")
    pdf.table_row("Australian Equities managers", "+0.10%")
    pdf.table_row("International Equities managers", "+0.08%")
    pdf.table_row("Fixed Income managers", "+0.02%")
    pdf.table_row("Real Assets managers", "+0.02%")
    pdf.subsection("Interaction & Currency: -0.04%")
    pdf.body("Currency hedging cost -0.06%, partially offset by interaction effects of +0.02%.")
    pdf.body("Attribution analysis is prepared internally by the portfolio analytics team and verified by the independent risk function. Factor decomposition shows the primary return drivers were: value factor (+0.18%), momentum (+0.11%), quality (+0.08%), with a negative size contribution (-0.05%).")

    pdf.add_page()
    pdf.section("Asset Allocation — Current Positioning")
    pdf.table_row("Australian Equities", "33% (SAA: 30%, +3% overweight)")
    pdf.table_row("International Equities", "27% (SAA: 30%, -3% underweight)")
    pdf.table_row("Fixed Income", "13% (SAA: 15%, -2% underweight)")
    pdf.table_row("Real Assets", "13% (SAA: 10%, +3% overweight)")
    pdf.table_row("Alternatives", "10% (SAA: 10%, neutral)")
    pdf.table_row("Cash", "4% (SAA: 5%, -1% underweight)")
    pdf.body("Key positioning changes during the quarter: increased Australian equities exposure by 2% in February following improved domestic earnings outlook; reduced international equities by 2% on stretched US valuations; added 1% to real assets (infrastructure) on improved rate outlook.")

    pdf.add_page()
    pdf.section("Market Commentary")
    pdf.body("Q1 2026 saw continued resilience in equity markets despite mixed economic signals. The S&P/ASX 200 returned +3.2% driven by resources and financials. Global equities (MSCI World) returned +2.8% in AUD terms, with the US market leading on AI-related optimism.")
    pdf.body("Australian fixed income delivered +0.8% as the RBA held rates steady at 3.85%. Credit spreads compressed further, benefiting the fund's allocation to investment grade corporate bonds.")
    pdf.body("The Australian dollar appreciated 1.2% against the USD during the quarter, creating a slight headwind on unhedged international exposures.")

    pdf.add_page()
    pdf.section("Risk Metrics")
    pdf.table_row("Portfolio Volatility (realised, 3m)", "8.2% annualised")
    pdf.table_row("VaR (95%, 1-day)", "0.52%")
    pdf.table_row("Beta to S&P/ASX 200", "0.65")
    pdf.table_row("Number of Holdings (total)", "847 (across underlying managers)")
    pdf.table_row("Top 10 Concentration", "12.3% of total fund")

    pdf.add_page()
    pdf.section("Outlook & Positioning Changes")
    pdf.body("Looking ahead to Q2 2026, the investment team maintains a moderately pro-growth stance. Key views:")
    pdf.bullet("Domestic equities: Remain overweight. Earnings growth supported by resources and housing recovery.")
    pdf.bullet("International equities: Neutral to slightly underweight. US valuations stretched; prefer Europe and Japan on relative value.")
    pdf.bullet("Fixed income: Remain underweight duration. Expect RBA to begin cutting in H2 2026, but timing uncertain.")
    pdf.bullet("Real assets: Maintain overweight. Infrastructure benefits from energy transition capex cycle.")

    pdf.save("pf_amp001_quarterly.pdf")


def gen_ddq():
    pdf = DocPDF("AMP Growth Fund - DDQ Response")
    pdf.cover_page("AMP Capital Investors", "Due Diligence Questionnaire Response\nAMP Growth Fund", "March 2026", "AMP Capital Investors Limited")

    pdf.add_page()
    pdf.section("1. Risk Management Framework")
    pdf.body("AMP Capital operates a three-lines-of-defence risk management framework:")
    pdf.bullet("First line: Portfolio managers and investment teams are responsible for identifying and managing risks within their mandates.")
    pdf.bullet("Second line: Independent Risk team (8 professionals) provides oversight, monitoring, and challenge.")
    pdf.bullet("Third line: Internal Audit provides independent assurance on the effectiveness of risk controls.")
    pdf.subsection("Risk Governance")
    pdf.body("The Risk Committee meets monthly and comprises the CIO, Head of Risk, CFO, and two independent non-executive directors. The committee reviews:")
    pdf.bullet("Portfolio risk metrics vs limits (VaR, CVaR, tracking error, concentration)")
    pdf.bullet("Stress test results (scenarios updated quarterly)")
    pdf.bullet("Operational risk events and near-misses")
    pdf.bullet("Model risk assessments")
    pdf.subsection("Quantitative Risk Limits")
    pdf.table_row("Portfolio VaR (95%, 1-day)", "Limit: 1.0% of NAV")
    pdf.table_row("CVaR (95%, 1-day)", "Limit: 1.5% of NAV")
    pdf.table_row("Maximum Drawdown Trigger", "-15% from peak (triggers IC review)")
    pdf.table_row("Tracking Error vs SAA", "Hard limit: 8% p.a.")
    pdf.table_row("Single Issuer Limit", "5% of NAV")
    pdf.body("Escalation procedures: Any limit breach triggers immediate notification to the Head of Risk, who must inform the Risk Committee Chair within 4 hours. The portfolio manager has 5 business days to rectify the breach. Persistent breaches (>10 days) are escalated to the Board.")

    pdf.add_page()
    pdf.section("2. Operational Infrastructure")
    pdf.subsection("Custodian")
    pdf.body("The fund's custodian is State Street Australia Limited (ABN 21 002 491 833), an APRA-regulated authorised deposit-taking institution. State Street provides custody, fund accounting, unit pricing, and registry services.")
    pdf.subsection("Systems")
    pdf.table_row("Order Management System", "Bloomberg AIM")
    pdf.table_row("Portfolio Management System", "SimCorp Dimension")
    pdf.table_row("Risk System", "MSCI RiskMetrics / Barra")
    pdf.table_row("Compliance Monitoring", "FIS Protegent (automated pre/post-trade)")
    pdf.table_row("Reconciliation", "Daily automated recon (Duco)")
    pdf.subsection("External Audit")
    pdf.body("The fund is audited annually by PricewaterhouseCoopers (PwC). The most recent audit opinion (30 June 2025) was unqualified. PwC also provides the annual GS007 assurance report on custody and administration controls.")
    pdf.body("ISAE 3402 (SOC 1 Type II) reports are obtained annually from State Street covering custody and fund administration controls. The most recent report (December 2025) had no exceptions noted.")

    pdf.add_page()
    pdf.section("3. Key Person Risk & Succession")
    pdf.body("The AMP Growth Fund's investment process is team-based, reducing reliance on any single individual. Key mitigation measures:")
    pdf.bullet("All investment decisions require Investment Committee approval (minimum 3 of 5 members)")
    pdf.bullet("The CIO is not the sole decision-maker; the lead PM and Deputy CIO have co-authority")
    pdf.bullet("All PMs have designated deputies who attend all IC meetings")
    pdf.bullet("Documented investment process ensures continuity regardless of personnel changes")
    pdf.subsection("Team Depth")
    pdf.table_row("Total investment team", "18 professionals")
    pdf.table_row("Average tenure", "8.2 years")
    pdf.table_row("PM team average experience", "18 years")
    pdf.table_row("Staff turnover (3-year avg)", "12%")
    pdf.body("Succession plan: Formal succession plans exist for all senior roles. The Deputy CIO (15 years tenure) is the designated successor for the CIO role. Portfolio manager succession is documented and reviewed annually by the Board.")
    pdf.body("Key person clause in PDS: The PDS discloses that Anna Shelley (CIO) and the senior portfolio management team are material to the fund's investment process. A change in CIO triggers notification to investors within 10 business days.")

    pdf.add_page()
    pdf.section("4. Business Continuity & Disaster Recovery")
    pdf.body("AMP Capital maintains a comprehensive Business Continuity Plan (BCP) and Disaster Recovery (DR) framework:")
    pdf.subsection("BCP Key Parameters")
    pdf.table_row("Recovery Time Objective (RTO)", "4 hours for critical systems")
    pdf.table_row("Recovery Point Objective (RPO)", "1 hour (real-time replication)")
    pdf.table_row("Alternate Site", "Fully equipped DR site in Parramatta, NSW")
    pdf.table_row("Remote Work Capability", "100% of investment team can work remotely")
    pdf.subsection("Testing")
    pdf.body("BCP/DR testing is conducted semi-annually. The most recent test (November 2025) achieved full recovery of trading systems within 2.5 hours (within RTO). All investment staff successfully connected to DR site and executed simulated trades.")
    pdf.body("COVID-era experience: During 2020-21, the firm operated fully remotely for 14 months with no disruption to fund operations, trading, or client reporting. This experience validated the DR framework and led to permanent hybrid work arrangements and enhanced technology infrastructure.")
    pdf.body("The BCP is reviewed annually by the Board and updated for changes in technology, personnel, or premises. The most recent full review was completed in September 2025.")

    pdf.add_page()
    pdf.section("5. Compliance Program")
    pdf.body("AMP Capital's compliance program is structured around the requirements of AFSL 232030 and supervised by the Chief Compliance Officer (CCO), who reports directly to the Board.")
    pdf.subsection("Framework Components")
    pdf.bullet("Annual compliance plan approved by the Board (updated January 2026)")
    pdf.bullet("Automated trade surveillance (pre-trade and post-trade checks)")
    pdf.bullet("Quarterly compliance reporting to the Risk & Compliance Committee")
    pdf.bullet("Mandatory compliance training for all staff (annual completion rate: 100%)")
    pdf.bullet("Whistleblower policy and hotline (independent third-party operated)")
    pdf.subsection("Breach Register")
    pdf.body("AMP Capital maintains a breach register as required under AFSL conditions. In the past three years, the AMP Growth Fund has recorded:")
    pdf.bullet("0 significant breaches reported to ASIC")
    pdf.bullet("3 minor operational breaches (all self-identified, rectified within 24 hours, no client impact)")
    pdf.bullet("0 enforceable undertakings or infringement notices")
    pdf.body("Minor breaches related to: one delayed trade reporting (system error), one temporary exceedance of cash limit by 0.2% (corrected same day), and one late filing of a routine regulatory return (1 day).")

    pdf.add_page()
    pdf.section("6. Conflicts of Interest Management")
    pdf.body("AMP Capital's Conflicts of Interest Policy covers the following areas:")
    pdf.subsection("Related Party Transactions")
    pdf.body("The AMP Growth Fund may invest in sub-funds managed by AMP Capital or affiliated entities. All such investments are made on arms-length terms and are subject to fee rebates that eliminate double-charging. Related party investments are disclosed in the fund's annual report and require independent director approval.")
    pdf.subsection("Personal Trading")
    pdf.body("All investment staff are subject to a Personal Trading Policy that requires:")
    pdf.bullet("Pre-clearance of all personal securities trades via automated system")
    pdf.bullet("30-day minimum holding period for all personal investments")
    pdf.bullet("Prohibition on trading securities on the fund's active buy/sell list")
    pdf.bullet("Quarterly certification of compliance with the policy")
    pdf.bullet("Annual disclosure of all brokerage accounts")
    pdf.subsection("Soft Dollar Policy")
    pdf.body("AMP Capital does not accept soft dollar arrangements. All brokerage commissions are allocated solely on best execution criteria. The firm conducts annual best execution reviews and reports outcomes to the Board.")
    pdf.subsection("Board Independence")
    pdf.body("The Responsible Entity Board comprises 6 directors, of whom 4 are independent non-executive directors. The Board Chair (independent) has no other commercial relationship with AMP Group. The Investment Committee includes one independent member.")

    pdf.add_page()
    pdf.section("7. Business Viability & Financial Stability")
    pdf.body("AMP Capital Investors Limited is a wholly-owned subsidiary of AMP Limited (ASX: AMP). Key financial indicators:")
    pdf.table_row("Parent Company", "AMP Limited (ASX: AMP)")
    pdf.table_row("Parent Market Cap", "~AUD 4.5 billion")
    pdf.table_row("AMP Capital Revenue", "AUD 485 million (FY2025)")
    pdf.table_row("Net Profit", "AUD 89 million (FY2025)")
    pdf.table_row("Capital Adequacy", "Exceeds ASIC Financial Requirements")
    pdf.subsection("AUM Trend")
    pdf.table_row("Dec 2023", "AUD 54.8 billion")
    pdf.table_row("Dec 2024", "AUD 56.5 billion")
    pdf.table_row("Dec 2025", "AUD 58.2 billion")
    pdf.table_row("3-Year CAGR", "+4.2%")
    pdf.subsection("Staff Retention")
    pdf.body("AMP Capital has maintained stable staffing levels with below-industry turnover:")
    pdf.table_row("Total staff (investment)", "142")
    pdf.table_row("Voluntary turnover (2025)", "12% (industry: 18%)")
    pdf.table_row("Average tenure (investment)", "7.8 years")
    pdf.body("The firm has not undertaken any significant redundancy programs in the past 3 years. Recruitment in 2025 focused on quantitative and technology roles to support process evolution.")

    # Pad to ~16 pages
    for i in range(8):
        pdf.add_page()
        if i == 0:
            pdf.section("8. Technology & Cyber Security")
            pdf.body("AMP Capital's technology infrastructure is enterprise-grade with the following security measures:")
            pdf.bullet("ISO 27001 certified information security management system")
            pdf.bullet("Annual penetration testing by independent assessors (most recent: October 2025, no critical findings)")
            pdf.bullet("Multi-factor authentication for all systems access")
            pdf.bullet("Real-time security monitoring via SOC (Security Operations Centre)")
            pdf.bullet("Quarterly vulnerability assessments")
            pdf.bullet("Mandatory cyber security training for all staff (phishing simulations monthly)")
        elif i == 1:
            pdf.section("9. Valuation Policy")
            pdf.body("The fund's valuation policy follows ASIC Regulatory Guide 94 requirements:")
            pdf.bullet("Listed securities: Last traded price on relevant exchange at valuation point")
            pdf.bullet("Unlisted assets: Independent valuation at least annually; internal valuation quarterly")
            pdf.bullet("Fixed income: Priced by independent pricing services (Bloomberg, ICE)")
            pdf.bullet("Derivatives: Mark-to-market using independent pricing feeds")
            pdf.body("A Valuation Committee meets monthly to review pricing exceptions and stale prices. Material valuation adjustments require CIO and CFO sign-off.")
        elif i == 2:
            pdf.section("10. Counterparty & Credit Risk")
            pdf.body("AMP Capital manages counterparty risk through:")
            pdf.bullet("Minimum credit rating of A- for OTC derivative counterparties")
            pdf.bullet("Daily margining on all OTC derivative positions")
            pdf.bullet("ISDA Master Agreements with all derivative counterparties")
            pdf.bullet("Counterparty exposure limits monitored daily")
            pdf.bullet("Central clearing for all standardised derivatives")
        elif i == 3:
            pdf.section("11. Liquidity Management")
            pdf.body("The fund maintains a liquidity management framework to meet redemption obligations:")
            pdf.bullet("Minimum 80% of portfolio realisable within 7 days under normal conditions")
            pdf.bullet("Stress testing of liquidity under adverse scenarios (quarterly)")
            pdf.bullet("Liquidity buffer of 2-5% cash/near-cash maintained at all times")
            pdf.bullet("Monitoring of fund flow patterns and large unitholder concentrations")
        elif i == 4:
            pdf.section("12. Proxy Voting & Stewardship")
            pdf.body("AMP Capital exercises voting rights on all equity holdings in accordance with its Proxy Voting Policy:")
            pdf.bullet("Voted on 98% of eligible resolutions in FY2025")
            pdf.bullet("Voted against management on 14% of resolutions (primarily remuneration and board composition)")
            pdf.bullet("Engaged directly with 85 companies on ESG issues in FY2025")
            pdf.bullet("Published annual Stewardship Report")
        elif i == 5:
            pdf.section("13. Distribution Policy")
            pdf.body("The AMP Growth Fund distributes income semi-annually (June and December). Distributions comprise dividends, interest, and realised capital gains. The fund does not maintain a managed payout or smoothing mechanism — distributions reflect actual income earned.")
        elif i == 6:
            pdf.section("14. Regulatory & Legal")
            pdf.body("AMP Capital confirms the following:")
            pdf.bullet("AFSL 232030 is current and in good standing")
            pdf.bullet("No current or pending regulatory actions, investigations, or proceedings")
            pdf.bullet("No material litigation relating to the AMP Growth Fund")
            pdf.bullet("Compliant with all APRA and ASIC reporting obligations")
            pdf.bullet("Member of Australian Financial Complaints Authority (AFCA)")
            pdf.bullet("Professional Indemnity insurance maintained at appropriate levels")
        else:
            pdf.section("15. Appendix — Organisational Chart")
            pdf.body("Board of Directors (Responsible Entity)")
            pdf.body("  -> Chief Executive Officer")
            pdf.body("     -> Chief Investment Officer (Anna Shelley)")
            pdf.body("        -> Head of Multi-Asset (Lead PM, AMP Growth Fund)")
            pdf.body("        -> Head of Australian Equities")
            pdf.body("        -> Head of Fixed Income")
            pdf.body("        -> Head of Real Assets")
            pdf.body("     -> Chief Risk Officer")
            pdf.body("        -> Head of Investment Risk")
            pdf.body("        -> Head of Operational Risk")
            pdf.body("     -> Chief Compliance Officer")
            pdf.body("     -> Chief Financial Officer")
            pdf.body("     -> Chief Operating Officer")

    pdf.save("pf_amp001_ddq.pdf")


if __name__ == "__main__":
    print("Generating AMP Growth Fund documents...")
    gen_pds()
    gen_quarterly()
    gen_ddq()
    print("Done!")
