"""Generate source documents for pf_hyperion001 -- Hyperion Australian Growth Companies."""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from pdf_helpers import DocPDF


def gen_pds():
    pdf = DocPDF("Hyperion Australian Growth Companies - PDS")
    pdf.cover_page("Hyperion Australian Growth Companies Fund", "Product Disclosure Statement", "1 January 2026", "Hyperion Asset Management Limited")

    pdf.add_page()
    pdf.section("1. About Hyperion Asset Management")
    pdf.body("Hyperion Asset Management Limited (ABN 80 080 135 897, AFSL 238380) is the investment manager of the Hyperion Australian Growth Companies Fund. Founded in 1996 in Brisbane, Hyperion is a specialist quality-growth equity manager with a singular focus on identifying and owning Australia's highest-quality businesses.")
    pdf.table_row("ABN", "80 080 135 897")
    pdf.table_row("AFSL", "238380")
    pdf.table_row("Founded", "1996")
    pdf.table_row("Headquarters", "Brisbane, QLD")
    pdf.table_row("Total AUM", "AUD 8.3 billion")
    pdf.table_row("Ownership", "Employee-owned (majority)")
    pdf.body("AFSL 238380 is current and in good standing. There are no enforceable undertakings issued by ASIC against Hyperion Asset Management. The firm has operated for 30 years with an unblemished regulatory record.")
    pdf.body("Hyperion's ownership structure is distinctive: the firm is majority employee-owned, with key investment staff holding significant equity stakes. This alignment of interest with clients is a core cultural value. The firm manages a single strategy (Australian equities) across different vehicle structures, ensuring complete focus.")

    pdf.add_page()
    pdf.section("2. Investment Philosophy & Process")
    pdf.body("The Hyperion Australian Growth Companies Fund is a high-conviction, concentrated portfolio of quality growth companies. The fund seeks to outperform the S&P/ASX All Ordinaries Accumulation Index over rolling 5-year periods through ownership of structural growth businesses at reasonable valuations.")
    pdf.body("Investment philosophy -- 'Modern Monopolies':")
    pdf.bullet("Invest in businesses with sustainable competitive advantages ('economic moats') that enable above-average earnings growth for extended periods (10+ years)")
    pdf.bullet("Quality of business is paramount: high returns on invested capital, strong management, large addressable markets, and network effects or switching costs")
    pdf.bullet("Valuation discipline: only invest when the quality business is available at a reasonable price relative to its long-term intrinsic value growth")
    pdf.bullet("Long holding periods: the power of compounding means the best returns come from holding truly great businesses for many years")
    pdf.subsection("Alpha Sources")
    pdf.body("Alpha is generated primarily from: (1) identifying quality businesses earlier than the market consensus recognises their structural growth potential, (2) maintaining conviction during short-term volatility when the market over-discounts temporary headwinds for quality companies, and (3) the compounding effect of owning businesses growing intrinsic value at 10-15% p.a. over very long periods.")
    pdf.subsection("Process Evolution")
    pdf.body("The investment process has remained remarkably consistent since Hyperion's founding in 1996. The core philosophy of owning quality growth businesses at reasonable prices has not changed. Key evolutions: (1) In 2010, formal integration of ESG considerations into quality assessment, recognising that poor ESG practices signal management quality issues. (2) In 2018, increased focus on 'digital moats' and network-effect businesses reflecting structural shift in economy. (3) In 2022, enhanced quantitative screening to more efficiently filter the research pipeline while maintaining fundamentally-driven final decisions.")

    pdf.add_page()
    pdf.section("3. Portfolio Construction")
    pdf.body("The fund is highly concentrated, reflecting Hyperion's conviction-based approach:")
    pdf.table_row("Target Holdings", "15-30 stocks")
    pdf.table_row("Current Holdings", "22")
    pdf.table_row("Typical Active Share", "70-85%")
    pdf.table_row("Max Single Stock", "10% at cost, 15% at market")
    pdf.table_row("Max Sector Weight", "40%")
    pdf.table_row("Off-Benchmark Allowance", "Up to 20% (ex-All Ords)")
    pdf.table_row("Cash Range", "0-20%")
    pdf.table_row("Current Cash", "8%")
    pdf.body("Position sizing reflects conviction: Tier 1 (highest conviction, 5-10%); Tier 2 (high conviction, 3-5%); Tier 3 (developing position, 1-3%). New positions start at Tier 3 and are built over 3-6 months as thesis develops.")
    pdf.body("The fund's concentration is intentional: Hyperion believes that dilution of capital across too many ideas reduces the benefit of owning truly exceptional businesses. However, concentration limits ensure no single position can permanently impair the portfolio.")
    pdf.body("Cash: Hyperion will hold elevated cash (up to 20%) when insufficient quality opportunities are available at reasonable prices. Cash is seen as a strategic asset providing optionality, not a drag on performance.")

    pdf.add_page()
    pdf.section("4. Benchmark & Objectives")
    pdf.table_row("Benchmark", "S&P/ASX All Ordinaries Accumulation Index")
    pdf.table_row("Objective", "Outperform benchmark by 4-5% p.a. (gross)")
    pdf.table_row("Time Horizon", "Rolling 5-year periods")
    pdf.table_row("Risk Profile", "Concentrated; expect higher short-term volatility")
    pdf.body("The S&P/ASX All Ordinaries Accumulation Index was selected because it is the broadest measure of the Australian equity market (~500 stocks), encompassing the full range of companies that Hyperion may consider. The All Ordinaries is more appropriate than the ASX 300 for Hyperion's concentrated, high-active-share approach as it captures the smaller growth companies that form part of the investable universe.")
    pdf.body("The benchmark has been used since fund inception in August 1996 and has not been changed. Benchmark appropriateness is reviewed annually by the Board.")

    pdf.add_page()
    pdf.section("5. Key Personnel")
    pdf.subsection("Mark Arnold -- Chief Investment Officer & Managing Director")
    pdf.body("Mark Arnold founded Hyperion Asset Management in 1996 and has served as CIO for the fund's entire 30-year history. He has over 35 years of investment experience. Mark holds a Bachelor of Commerce (Hons) from the University of Queensland and is a CFA charterholder. He personally holds a significant equity stake in Hyperion, aligning his interests with investors.")
    pdf.subsection("Investment Team")
    pdf.body("The investment team is deliberately lean, comprising 7 professionals:")
    pdf.bullet("CIO/Lead PM: Mark Arnold (35 years experience)")
    pdf.bullet("Deputy CIO/Co-PM: Jason Orthman (18 years experience, 15 at Hyperion)")
    pdf.bullet("3 Research Analysts (covering different sectors, avg 12 years experience)")
    pdf.bullet("1 Quantitative Analyst")
    pdf.bullet("1 ESG/Stewardship Analyst")
    pdf.table_row("Average tenure", "11.2 years")
    pdf.table_row("Average experience", "19 years")
    pdf.body("Key person risk: Mark Arnold is the founder and has managed this fund for 30 years. His departure would be a material event. Mitigation: Jason Orthman (Deputy CIO) has co-managed the fund since 2011 and has full authority to run the strategy independently. The investment philosophy and process are deeply embedded in the team culture. All team members hold equity in Hyperion, providing retention incentives.")
    pdf.body("Key person clause: The PDS discloses Mark Arnold as a key person. Departure triggers investor notification within 5 business days.")

    pdf.add_page()
    pdf.section("6. ESG Integration")
    pdf.body("ESG is integrated into Hyperion's quality assessment framework. Poor ESG practices are considered a proxy for management quality issues and can disqualify a company regardless of financial metrics.")
    pdf.bullet("UNPRI signatory since 2010")
    pdf.bullet("ESG assessment: All potential investments assessed on governance quality, environmental risk management, and social licence to operate")
    pdf.bullet("Exclusions: Tobacco, controversial weapons, thermal coal (>10% revenue)")
    pdf.bullet("Engagement: Direct engagement with all 22 portfolio companies annually on material ESG issues")
    pdf.bullet("Voting: 100% of proxies voted in FY2025; voted against management on 15% of resolutions (primarily remuneration)")
    pdf.body("Hyperion's view: The best-quality businesses tend to have strong ESG practices because good management teams manage all stakeholder relationships well. ESG integration is therefore a natural extension of the quality focus, not a constraint.")

    pdf.add_page()
    pdf.section("7. Conflicts of Interest")
    pdf.bullet("Ownership: Majority employee-owned; no external parent with conflicting interests")
    pdf.bullet("Single strategy: Hyperion manages one strategy, eliminating inter-fund allocation conflicts")
    pdf.bullet("Personal trading: All staff subject to pre-clearance, 60-day hold (longer than industry standard), prohibition on trading any stock in the portfolio or under research")
    pdf.bullet("Soft dollars: Not accepted. All research conducted internally.")
    pdf.bullet("Board: 5 directors, 3 independent (Chair is independent)")
    pdf.bullet("No affiliated service providers (custodian, broker, administrator all independent)")
    pdf.body("The employee-owned, single-strategy structure eliminates many common conflicts found at larger, multi-strategy firms. This simplicity is intentional and highly valued by Hyperion's long-term institutional clients.")

    pdf.add_page()
    pdf.section("8. Fees & Costs")
    pdf.table_row("Management Fee (MER)", "1.10% p.a. of NAV")
    pdf.table_row("Performance Fee", "Nil")
    pdf.table_row("Indirect Cost Ratio (ICR)", "0.00%")
    pdf.table_row("Buy Spread", "0.20%")
    pdf.table_row("Sell Spread", "0.20%")
    pdf.table_row("Entry/Exit Fees", "Nil")
    pdf.body("Hyperion's management fee is at the higher end of the Australian equities peer group, reflecting the firm's concentrated, high-conviction approach with a strong long-term track record. There is no performance fee -- the firm believes the base fee should be set at a level that supports a quality team without the agency problems that performance fees can create.")
    pdf.body("The zero ICR reflects direct investment in ASX-listed stocks with no underlying fund structures.")
    pdf.body("Buy/sell spreads of 0.20% reflect the somewhat higher transaction costs of trading concentrated positions (larger trades relative to fund size). Spreads are reviewed quarterly.")
    pdf.body("Total estimated cost: 1.10% p.a. plus applicable spreads. The higher fee is justified by the fund's strong long-term outperformance track record (since-inception excess return of ~4% p.a. net of fees).")

    pdf.add_page()
    pdf.section("9. Business Viability")
    pdf.table_row("Fund AUM", "AUD 5,100 million")
    pdf.table_row("Fund Inception", "1 August 1996")
    pdf.table_row("APIR Code", "WHT8435AU")
    pdf.table_row("Firm Total AUM", "AUD 8.3 billion")
    pdf.table_row("3-Year AUM Growth", "+5.2% CAGR")
    pdf.table_row("Staff Turnover", "5% (exceptionally low)")
    pdf.body("Hyperion is well-established with AUD 8.3 billion under management across its single strategy (offered in multiple vehicles). The firm's 30-year track record and concentrated, capacity-aware approach has built a loyal institutional and wholesale client base.")
    pdf.body("The employee ownership structure provides strong retention incentives. Staff turnover of 5% is exceptionally low in the industry. The investment team has been stable for over a decade, with no senior departures since 2013.")
    pdf.body("Capacity management: Hyperion has historically soft-closed to new investors when AUM levels risked impacting the concentrated strategy's ability to invest in smaller growth companies. This disciplined approach to capacity prioritises existing investor outcomes over revenue growth.")
    pdf.subsection("AUM Trend")
    pdf.table_row("Dec 2023", "AUD 7.4 billion")
    pdf.table_row("Dec 2024", "AUD 7.9 billion")
    pdf.table_row("Dec 2025", "AUD 8.3 billion")

    # Pad to ~18 pages
    for i in range(8):
        pdf.add_page()
        if i == 0:
            pdf.section("10. Risk Disclosures")
            pdf.body("Key risks of the Hyperion Australian Growth Companies Fund:")
            pdf.bullet("Concentration risk: With 15-30 holdings, individual stock events materially impact performance. This is the primary risk of the strategy.")
            pdf.bullet("Style risk: Quality-growth style may underperform in value-driven markets (as seen in 2022)")
            pdf.bullet("Key person risk: Reliance on Mark Arnold and Jason Orthman")
            pdf.bullet("Valuation risk: Growth companies trade at premium valuations; de-rating can cause significant drawdowns")
            pdf.bullet("Cash drag: Elevated cash positions may reduce returns in strong bull markets")
        elif i == 1:
            pdf.section("11. Regulatory Information")
            pdf.bullet("AFSL 238380 current, good standing")
            pdf.bullet("No enforceable undertakings (30-year history)")
            pdf.bullet("No regulatory actions or proceedings")
            pdf.bullet("AFCA member")
            pdf.body("Hyperion's 30-year regulatory record is clean. The firm's focused, single-strategy approach reduces operational complexity and associated regulatory risk.")
        elif i == 2:
            pdf.section("12. Governance")
            pdf.bullet("Board: 5 directors, 3 independent (Chair independent)")
            pdf.bullet("Investment Committee: CIO (Mark Arnold) + Deputy CIO (Jason Orthman)")
            pdf.bullet("Risk Committee: 2 independent directors + CFO")
            pdf.bullet("External auditor: Ernst & Young")
            pdf.bullet("Custodian: National Australia Bank (APRA-regulated)")
        elif i == 3:
            pdf.section("13. Compliance Framework")
            pdf.bullet("Compliance team: 3 professionals (scaled for firm size)")
            pdf.bullet("CCO reports to Board")
            pdf.bullet("Annual compliance plan (approved January 2026)")
            pdf.bullet("Automated post-trade compliance monitoring")
            pdf.bullet("Breach register: Zero breaches in past 3 years")
            pdf.bullet("Annual compliance training: 100% completion")
        elif i == 4:
            pdf.section("14. Minimum Investment & Access")
            pdf.table_row("Minimum Initial Investment", "AUD 25,000")
            pdf.table_row("Minimum Additional", "AUD 5,000")
            pdf.body("The higher minimum investment reflects Hyperion's institutional heritage and the fund's target market of sophisticated investors who understand concentrated equity strategies. The fund is primarily distributed via institutional mandates and financial adviser platforms.")
        elif i == 5:
            pdf.section("15. Distribution & Tax")
            pdf.body("Annual distribution in June. Comprising dividends (including franking credits) and realised capital gains. The fund is a low-turnover strategy (typically <20% p.a.) resulting in tax-efficient outcomes for investors.")
            pdf.body("AMIT regime applies. AMMA statements provided.")
        elif i == 6:
            pdf.section("16. Withdrawals")
            pdf.body("Daily redemptions, processed within 5 business days. The fund's focus on liquid ASX-listed equities ensures redemptions can be met without portfolio disruption. No gates or notice periods under normal conditions.")
        else:
            pdf.section("17. Contact")
            pdf.body("Hyperion Asset Management Limited")
            pdf.body("Phone: (07) 3232 0100")
            pdf.body("Email: info@hyperionam.com.au")
            pdf.body("Website: www.hyperionam.com.au")
            pdf.body("Address: Level 12, 100 Creek Street, Brisbane QLD 4000")

    pdf.save("pf_hyperion001_pds.pdf")


def gen_quarterly():
    pdf = DocPDF("Hyperion - Q1 2026 Investment Letter")
    pdf.cover_page("Hyperion Australian Growth Companies Fund", "Investment Letter\nQ1 2026 (January - March)", "April 2026", "Hyperion Asset Management Limited")

    pdf.add_page()
    pdf.section("Dear Investor")
    pdf.body("The Hyperion Australian Growth Companies Fund returned +5.2% (after fees) for the quarter ended 31 March 2026, outperforming the S&P/ASX All Ordinaries Accumulation Index return of +3.2% by 2.0%.")
    pdf.table_row("Fund Return (Q1 2026)", "+5.2% (after fees)")
    pdf.table_row("All Ords Accumulation Index", "+3.2%")
    pdf.table_row("Excess Return", "+2.0%")
    pdf.table_row("1 Year Return", "+18.5%")
    pdf.table_row("3 Year Return (p.a.)", "+12.8%")
    pdf.table_row("5 Year Return (p.a.)", "+11.2%")
    pdf.table_row("Since Inception (p.a.)", "+13.4% (vs index 9.1%)")
    pdf.table_row("Tracking Error (3yr)", "7.2% p.a.")
    pdf.table_row("Information Ratio (3yr)", "0.53")
    pdf.table_row("Active Share", "78%")
    pdf.table_row("Number of Holdings", "22")
    pdf.table_row("Cash", "8%")

    pdf.add_page()
    pdf.section("Performance Attribution")
    pdf.body("The fund's outperformance in Q1 was driven by our quality growth holdings benefiting from renewed appreciation of structural earnings growth:")
    pdf.subsection("Top Contributors")
    pdf.table_row("CSL Limited (+12%)", "+1.1% contribution (largest holding)")
    pdf.table_row("Xero Limited (+18%)", "+0.8% (digital platform growth)")
    pdf.table_row("WiseTech Global (+15%)", "+0.6% (logistics SaaS)")
    pdf.table_row("Cochlear (+9%)", "+0.4% (healthcare innovation)")
    pdf.subsection("Top Detractors")
    pdf.table_row("Altium (flat)", "-0.2% (semiconductor headwind)")
    pdf.table_row("Cash (8% allocation)", "-0.3% (opportunity cost)")
    pdf.body("Factor attribution: Quality (+1.8%), Momentum (+0.6%), Growth (+0.4%), Size (-0.3%), Value (-0.5%). The quality and growth factor exposure reflects the fund's structural positioning.")
    pdf.body("Brinson attribution: Stock selection contributed +2.4%, offset by sector allocation -0.1% and cash drag -0.3%.")

    pdf.add_page()
    pdf.section("Investment Commentary")
    pdf.body("Our philosophy remains unchanged: we seek to own a concentrated portfolio of Australia's highest-quality businesses -- companies with sustainable competitive advantages growing intrinsic value at attractive rates. In Q1, the market began to re-appreciate the value of quality and structural growth after a period of value outperformance in 2024-25.")
    pdf.body("We made minimal changes to the portfolio during the quarter. One new position was initiated (a Tier 3 starter in an emerging software platform) and one position was sold completely (a financial services company where we assessed the competitive moat was narrowing). Turnover for the quarter was 4% (annualised: ~16%).")
    pdf.body("Cash remains at 8%, reflecting our discipline in only deploying capital when quality opportunities are available at reasonable prices. We continue to believe that maintaining cash optionality is more valuable than forcing capital into lower-quality ideas.")

    pdf.add_page()
    pdf.section("Benchmark Comparison & Outlook")
    pdf.body("The fund's tracking error of 7.2% reflects the highly differentiated nature of our portfolio relative to the All Ordinaries. Our active share of 78% means we look very different from the benchmark, and periods of significant relative under- and outperformance are expected.")
    pdf.body("The All Ordinaries remains the appropriate benchmark for this fund. While the fund is concentrated in ~22 stocks, the benchmark's breadth (~500 stocks) captures the full universe of potential investments including the smaller growth companies that form part of our opportunity set.")
    pdf.body("Looking ahead, we see an attractive environment for quality growth companies. Lower interest rates (expected H2 2026) reduce the discount rate applied to long-duration growth assets. Structural trends in digital transformation, healthcare innovation, and the energy transition continue to benefit our holdings.")
    pdf.body("Risks we are monitoring: potential for renewed inflation (would hurt growth valuations), geopolitical disruption, and concentration of market returns in a narrow set of stocks globally.")

    pdf.save("pf_hyperion001_quarterly.pdf")


def gen_ddq():
    pdf = DocPDF("Hyperion Australian Growth Companies - DDQ Response")
    pdf.cover_page("Hyperion Asset Management", "Due Diligence Questionnaire Response\nHyperion Australian Growth Companies Fund", "March 2026", "Hyperion Asset Management Limited")

    pdf.add_page()
    pdf.section("1. Risk Management Framework")
    pdf.body("Hyperion's risk management reflects the concentrated nature of the strategy:")
    pdf.subsection("Risk Governance")
    pdf.bullet("Board Risk Committee: 2 independent directors + CFO, meets quarterly")
    pdf.bullet("Investment Committee: CIO (Mark Arnold) + Deputy CIO (Jason Orthman) -- meets weekly")
    pdf.bullet("External risk reporting: Monthly risk reports prepared by independent risk consultant")
    pdf.subsection("Quantitative Risk Limits")
    pdf.table_row("Maximum Single Stock", "10% at cost, 15% at market value")
    pdf.table_row("Maximum Sector Weight", "40%")
    pdf.table_row("Minimum Holdings", "15")
    pdf.table_row("Maximum Cash", "20%")
    pdf.table_row("Tracking Error (expected)", "5-10% p.a. (no hard limit)")
    pdf.table_row("Drawdown Review Trigger", "-20% from peak")
    pdf.body("Note: Hyperion deliberately does not impose VaR or CVaR limits. The firm's view is that volatility-based risk measures are inappropriate for a long-term, concentrated quality growth strategy where short-term drawdowns in quality names represent opportunities, not risks. The primary risk metric is permanent capital impairment, assessed qualitatively through ongoing fundamental research.")
    pdf.body("Escalation: Concentration limit breaches reported to Board within 24 hours. PM has 10 business days to bring within limits (longer than typical, reflecting concentrated strategy's needs). The -20% drawdown trigger activates a formal IC review of portfolio positioning and thesis integrity.")

    pdf.add_page()
    pdf.section("2. Operational Infrastructure")
    pdf.subsection("Service Providers")
    pdf.table_row("Custodian", "National Australia Bank (APRA-regulated)")
    pdf.table_row("Administrator", "Mainstream Fund Services")
    pdf.table_row("Registry", "Mainstream Fund Services")
    pdf.table_row("External Auditor", "Ernst & Young")
    pdf.subsection("Technology Systems")
    pdf.table_row("OMS/PMS", "Iress (XPLAN/ViewPoint)")
    pdf.table_row("Risk Analytics", "FactSet (outsourced risk reporting)")
    pdf.table_row("Compliance Monitoring", "Iress Compliance (post-trade)")
    pdf.table_row("Research", "Bloomberg Terminal + proprietary models")
    pdf.table_row("Reconciliation", "Daily (Mainstream vs NAB)")
    pdf.subsection("Audit & Controls")
    pdf.body("External audit (30 June 2025): Unqualified opinion by Ernst & Young.")
    pdf.body("GS007 report from NAB (December 2025): No exceptions.")
    pdf.body("Internal controls: While Hyperion does not have a formal internal audit function (appropriate for its size), key controls are tested annually by Ernst & Young as part of the financial audit. Segregation of duties is maintained between investment, operations, and compliance.")

    pdf.add_page()
    pdf.section("3. Key Person Risk & Team")
    pdf.body("Mark Arnold (CIO/Founder) is a significant key person for this fund. He has managed it for its entire 30-year history. This is the most material risk factor in the DDQ.")
    pdf.subsection("Mitigation Measures")
    pdf.bullet("Jason Orthman (Deputy CIO): 18 years experience, 15 at Hyperion. Co-manages the fund since 2011. Full authority and capability to run strategy independently.")
    pdf.bullet("Team culture: Investment philosophy deeply embedded in team. All decisions are collaborative.")
    pdf.bullet("Employee ownership: All investment team members hold equity, providing retention and alignment")
    pdf.bullet("Non-compete: 2-year non-compete for all investment staff")
    pdf.bullet("Documented process: While judgment-intensive, the investment framework is well-documented")
    pdf.subsection("Team Stability")
    pdf.table_row("Mark Arnold tenure", "30 years (founder)")
    pdf.table_row("Jason Orthman tenure", "15 years")
    pdf.table_row("Analyst average tenure", "8 years")
    pdf.table_row("Team turnover (5yr avg)", "5% (one departure in 5 years)")
    pdf.body("The 5% turnover is exceptionally low and reflects the employee ownership structure, Brisbane quality of life (vs Sydney/Melbourne), and strong team culture built around a singular investment philosophy.")
    pdf.body("Succession plan: Jason Orthman is the Board-designated successor to Mark Arnold. Transition planning documentation exists but Mark has indicated no plans to retire in the medium term.")

    pdf.add_page()
    pdf.section("4. Business Continuity & DR")
    pdf.table_row("RTO", "4 hours (trading capability)")
    pdf.table_row("RPO", "2 hours")
    pdf.table_row("DR Site", "Cloud-based + home trading capability")
    pdf.table_row("Remote Work", "All team members can trade from home")
    pdf.subsection("Testing")
    pdf.body("Annual BCP/DR test. Most recent (August 2025): Team operated from home for 2 days; all trading and reporting completed normally. The concentrated portfolio (22 stocks) makes operational continuity simpler than diversified strategies.")
    pdf.body("COVID validation: Fully remote operations March 2020 - September 2021. No disruptions. The small team and concentrated portfolio proved highly resilient.")
    pdf.body("BCP reviewed annually by the Board (last: July 2025). The firm's small size and simple operational model reduce BCP complexity relative to larger organisations.")

    pdf.add_page()
    pdf.section("5. Compliance & Regulatory")
    pdf.body("AFSL 238380 -- current, good standing, 30-year clean record.")
    pdf.bullet("Compliance team: 3 professionals (CCO + 2 compliance officers)")
    pdf.bullet("CCO reports to Board")
    pdf.bullet("Annual compliance plan (approved January 2026)")
    pdf.bullet("Post-trade compliance monitoring via Iress")
    pdf.bullet("Breach register: Zero breaches in past 3 years")
    pdf.bullet("Zero ASIC actions in firm's entire 30-year history")
    pdf.bullet("AFCA member")
    pdf.body("The firm's unblemished 30-year regulatory record, combined with its simple operating model (single strategy, Australian equities only, no derivatives, no leverage), contributes to low regulatory risk.")

    pdf.add_page()
    pdf.section("6. Conflicts of Interest")
    pdf.body("Hyperion's structure minimizes conflicts:")
    pdf.subsection("Structural Advantages")
    pdf.bullet("Single strategy: No inter-fund allocation conflicts")
    pdf.bullet("Employee-owned: No external parent with conflicting interests")
    pdf.bullet("No affiliated brokers or service providers")
    pdf.bullet("No soft dollars (all research internal)")
    pdf.subsection("Personal Trading")
    pdf.bullet("Pre-clearance required for all personal trades")
    pdf.bullet("60-day minimum hold (longer than industry standard of 30 days)")
    pdf.bullet("Cannot trade any stock in the portfolio or under research")
    pdf.bullet("Annual disclosure of all brokerage accounts")
    pdf.bullet("Quarterly compliance certification")
    pdf.subsection("Board Independence")
    pdf.body("5 directors: 3 independent, 2 executive (Mark Arnold, Jason Orthman). Chair is independent. The majority-independent Board provides oversight of a firm where key executives are also shareholders.")

    pdf.add_page()
    pdf.section("7. Business Viability")
    pdf.table_row("Firm Revenue (FY2025)", "AUD 88 million")
    pdf.table_row("Net Profit (FY2025)", "AUD 38 million")
    pdf.table_row("Total AUM (Dec 2025)", "AUD 8.3 billion")
    pdf.table_row("3-Year AUM CAGR", "+5.2%")
    pdf.table_row("Profit Margin", "~43%")
    pdf.subsection("AUM Trend")
    pdf.table_row("Dec 2023", "AUD 7.4 billion")
    pdf.table_row("Dec 2024", "AUD 7.9 billion")
    pdf.table_row("Dec 2025", "AUD 8.3 billion")
    pdf.subsection("Capacity & Growth")
    pdf.body("Hyperion has historically soft-closed to manage capacity. The firm estimates the strategy's capacity at approximately AUD 12-15 billion before market impact becomes meaningful. At AUD 8.3 billion, there is runway for continued growth without compromising returns.")
    pdf.subsection("Staff & Retention")
    pdf.table_row("Total employees", "28")
    pdf.table_row("Investment team", "7")
    pdf.table_row("Turnover (5yr avg)", "5%")
    pdf.body("The firm is highly profitable with significant free cash flow. Employee ownership provides both retention and alignment. No debt, no external investors in the management company. Financial stability is exceptional for a firm of this size.")

    # Pad to ~20 pages
    for i in range(12):
        pdf.add_page()
        if i == 0:
            pdf.section("8. Technology & Cyber Security")
            pdf.bullet("Annual penetration testing (last: July 2025, no critical findings)")
            pdf.bullet("MFA on all systems")
            pdf.bullet("Email security: advanced threat protection")
            pdf.bullet("Annual cyber security training for all staff")
            pdf.bullet("Incident response plan documented and tested")
            pdf.body("Hyperion's small size and simple technology stack (minimal external connectivity, no algorithmic trading, no automated execution) reduce cyber attack surface relative to larger, more complex firms.")
        elif i == 1:
            pdf.section("9. Investment Decision Process Detail")
            pdf.body("Stock selection process:")
            pdf.bullet("Step 1: Quantitative screening -- identify companies with ROIC >15%, revenue growth >7%, debt/equity <50%")
            pdf.bullet("Step 2: Qualitative assessment -- competitive advantage analysis (moat width, durability), management quality, addressable market size")
            pdf.bullet("Step 3: Valuation -- discounted cash flow model (10-year horizon), comparison to intrinsic value growth rate")
            pdf.bullet("Step 4: IC discussion -- formal presentation to CIO and Deputy CIO; unanimous agreement required for new position")
            pdf.bullet("Step 5: Position sizing -- Tier assignment based on conviction level")
            pdf.body("Average time from initial idea to portfolio inclusion: 3-6 months. The team is not pressured to generate new ideas rapidly; patience and thoroughness are valued over activity.")
        elif i == 2:
            pdf.section("10. Sell Discipline")
            pdf.body("Positions are sold when:")
            pdf.bullet("Competitive advantage has structurally deteriorated (moat narrowing)")
            pdf.bullet("Management quality declines (poor capital allocation, governance issues)")
            pdf.bullet("Valuation reaches extreme levels (>40x forward earnings with no acceleration)")
            pdf.bullet("A superior opportunity requires funding")
            pdf.body("Importantly, short-term share price declines are NOT a sell signal if the investment thesis remains intact. Hyperion has frequently added to positions during market selloffs.")
        elif i == 3:
            pdf.section("11. Proxy Voting & Engagement")
            pdf.body("With only 22 holdings, Hyperion engages deeply with each company:")
            pdf.table_row("Board/management meetings p.a.", "2-4 per company")
            pdf.table_row("Proxy votes cast (FY2025)", "100% of eligible")
            pdf.table_row("Votes against management", "15%")
            pdf.body("Key engagement topics: capital allocation discipline, executive remuneration alignment with long-term value creation, board composition and skills, climate/ESG disclosure quality.")
            pdf.body("The concentrated portfolio enables meaningful engagement -- management teams know Hyperion is a large, long-term holder and engagement carries weight.")
        elif i == 4:
            pdf.section("12. Liquidity")
            pdf.body("The fund invests exclusively in ASX-listed equities:")
            pdf.bullet("All 22 holdings are in the ASX 200 (highly liquid)")
            pdf.bullet("Average daily volume: all positions can be liquidated within 5 trading days under normal conditions")
            pdf.bullet("No unlisted investments, no derivatives, no structured products")
            pdf.bullet("Cash buffer of 8% provides additional liquidity cushion")
            pdf.body("Concentration risk: While positions are large relative to the fund, they are small relative to stock liquidity (largest position is <0.5% of stock's market cap).")
        elif i == 5:
            pdf.section("13. Performance Track Record Context")
            pdf.body("30-year track record highlights:")
            pdf.table_row("Since inception (Aug 1996)", "+13.4% p.a. (vs All Ords +9.1%)")
            pdf.table_row("Excess return (p.a.)", "+4.3% (gross), +3.2% (net of fees)")
            pdf.table_row("Outperformed in", "22 of 30 financial years (73%)")
            pdf.table_row("Largest calendar underperformance", "-8.2% (FY2022, value rotation)")
            pdf.table_row("Largest calendar outperformance", "+18.5% (FY2020, quality premium)")
            pdf.body("The track record demonstrates consistent outperformance through multiple market cycles. Periods of relative underperformance have been associated with narrow value-style rallies and typically recovered within 12-18 months.")
        elif i == 6:
            pdf.section("14. Capacity Management")
            pdf.body("Hyperion takes a disciplined approach to capacity:")
            pdf.bullet("Estimated strategy capacity: AUD 12-15 billion")
            pdf.bullet("Current AUM: AUD 8.3 billion (~60% of estimated capacity)")
            pdf.bullet("History of soft-closes: Fund was soft-closed 2017-2019, reopened selectively")
            pdf.bullet("Priority: Existing investor outcomes over AUM growth")
            pdf.body("As AUM approaches capacity estimates, the firm will progressively limit new investor access. This discipline is a key differentiator and protects existing investor returns.")
        elif i == 7:
            pdf.section("15. Valuation Policy")
            pdf.body("All holdings are ASX-listed equities valued at closing ASX price daily. No subjective valuation judgments required. Unit pricing is calculated by Mainstream Fund Services and reconciled against NAB (custodian) daily.")
        elif i == 8:
            pdf.section("16. Insurance")
            pdf.bullet("Professional Indemnity: AUD 40 million")
            pdf.bullet("Directors & Officers: AUD 20 million")
            pdf.bullet("Crime/Fidelity: AUD 15 million")
            pdf.bullet("Cyber: AUD 10 million")
        elif i == 9:
            pdf.section("17. Counterparty Risk")
            pdf.body("Minimal counterparty exposure:")
            pdf.bullet("No derivatives of any kind")
            pdf.bullet("No securities lending")
            pdf.bullet("No repurchase agreements")
            pdf.bullet("Cash held with NAB (APRA-regulated ADI)")
            pdf.body("The strategy's simplicity (direct ASX equity holdings + cash) means counterparty risk is limited to the custodian and cash deposit bank.")
        elif i == 10:
            pdf.section("18. Environmental Policy")
            pdf.body("Hyperion's ESG integration focuses on quality signals:")
            pdf.bullet("Companies with poor environmental practices often signal management quality issues")
            pdf.bullet("Portfolio carbon intensity: 45 tCO2e/$M revenue (well below benchmark)")
            pdf.bullet("Zero exposure to fossil fuel extraction or thermal coal")
            pdf.bullet("Climate risk considered in all company assessments via long-term DCF impact")
        else:
            pdf.section("19. Appendix -- Organisation Structure")
            pdf.body("Board of Directors (5 members, 3 independent)")
            pdf.body("  -> Mark Arnold (CIO & Managing Director)")
            pdf.body("     -> Jason Orthman (Deputy CIO)")
            pdf.body("        -> 3 Research Analysts")
            pdf.body("        -> 1 Quantitative Analyst")
            pdf.body("        -> 1 ESG/Stewardship Analyst")
            pdf.body("  -> Chief Financial Officer")
            pdf.body("     -> Operations (3 staff)")
            pdf.body("  -> Chief Compliance Officer")
            pdf.body("     -> Compliance (2 staff)")
            pdf.body("  -> Head of Distribution")
            pdf.body("     -> Client Services (4 staff)")
            pdf.body("")
            pdf.body("Total staff: 28")

    pdf.save("pf_hyperion001_ddq.pdf")


if __name__ == "__main__":
    print("Generating Hyperion Australian Growth Companies documents...")
    gen_pds()
    gen_quarterly()
    gen_ddq()
    print("Done!")
