"""Generate source documents for pf_aef001 -- Australian Ethical Balanced Fund."""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from pdf_helpers import DocPDF


def gen_pds():
    pdf = DocPDF("Australian Ethical Balanced Fund - PDS 2026")
    pdf.cover_page("Australian Ethical Balanced Fund", "Product Disclosure Statement 2026", "1 January 2026", "Australian Ethical Investment Limited")

    pdf.add_page()
    pdf.section("1. About Australian Ethical Investment")
    pdf.body("Australian Ethical Investment Limited (ABN 47 003 188 930, AFSL 229949) is the responsible entity and investment manager of the Australian Ethical Balanced Fund. Founded in 1986, Australian Ethical is one of Australia's pioneering ethical and responsible investment managers.")
    pdf.table_row("ABN", "47 003 188 930")
    pdf.table_row("AFSL", "229949")
    pdf.table_row("Founded", "1986")
    pdf.table_row("Headquarters", "Sydney, NSW")
    pdf.table_row("Total AUM", "AUD 10.7 billion")
    pdf.table_row("Ownership", "Listed on ASX (ASX: AEF)")
    pdf.body("AFSL 229949 is current and in good standing. There are no enforceable undertakings issued by ASIC against Australian Ethical Investment Limited. The firm has operated continuously for nearly 40 years with an unblemished regulatory record.")
    pdf.body("Australian Ethical is guided by the Australian Ethical Charter, a founding document that defines the ethical principles governing all investment decisions. The Charter is embedded in the company's constitution and cannot be amended without a special resolution of shareholders.")

    pdf.add_page()
    pdf.section("2. Investment Philosophy & Process")
    pdf.body("The Australian Ethical Balanced Fund invests in a diversified portfolio of Australian and international assets, guided by the Australian Ethical Charter. The fund targets returns above CPI + 3.5% per annum over rolling 5-year periods while applying rigorous ethical screening.")
    pdf.body("Investment philosophy -- the Ethical Charter approach:")
    pdf.bullet("Negative screening: Exclude companies and activities that cause harm to people, animals, or the environment (tobacco, weapons, fossil fuels, gambling, live animal export, old-growth logging)")
    pdf.bullet("Positive tilt: Actively seek companies providing solutions to social and environmental challenges (renewable energy, healthcare, education, sustainable agriculture)")
    pdf.bullet("Best-of-sector: Where engagement is more effective than exclusion, invest in sector leaders demonstrating genuine ESG improvement")
    pdf.subsection("Alpha Sources")
    pdf.body("The fund generates alpha through: (1) avoiding companies with hidden ESG tail risks that traditional analysis misses, (2) identifying undervalued companies benefiting from sustainability megatrends (energy transition, circular economy, digital inclusion), and (3) active engagement that unlocks shareholder value through improved corporate behaviour.")
    pdf.subsection("Process Evolution")
    pdf.body("The investment process has evolved significantly since 1986. The original approach was primarily exclusionary (negative screening). In 2015, the firm introduced a proprietary 'Ethical Scoring' framework that quantifies both harm (negative) and benefit (positive) impacts across 23 impact categories. In 2021, climate scenario analysis (TCFD-aligned) was integrated into the process. The 2023 enhancement added biodiversity impact assessment using the TNFD framework.")

    pdf.add_page()
    pdf.section("3. Portfolio Construction")
    pdf.body("The fund constructs a diversified multi-asset portfolio within ethical boundaries:")
    pdf.table_row("Australian Equities", "20-40% (SAA: 30%)")
    pdf.table_row("International Equities", "20-40% (SAA: 30%)")
    pdf.table_row("Fixed Income", "10-30% (SAA: 20%)")
    pdf.table_row("Property & Infrastructure", "0-15% (SAA: 10%)")
    pdf.table_row("Cash", "0-20% (SAA: 10%)")
    pdf.subsection("Concentration Limits")
    pdf.table_row("Max single stock", "6% at cost")
    pdf.table_row("Max single sector", "25% of equities")
    pdf.table_row("Max single country (ex-AU)", "25% of intl equities")
    pdf.table_row("Min ethical score", "Positive net impact required")
    pdf.body("The ethical screen reduces the investable universe by approximately 30-40% compared to unconstrained benchmarks. Portfolio construction actively manages this constraint to maintain diversification while ensuring all holdings meet the Charter's requirements.")
    pdf.body("Rebalancing is conducted quarterly to within +/-5% of SAA. Ethical screening is applied continuously -- any holding that breaches the Charter must be divested within 30 days of identification.")

    pdf.add_page()
    pdf.section("4. Benchmark & Objectives")
    pdf.table_row("Primary Benchmark", "CPI + 3.5% p.a.")
    pdf.table_row("Risk Objective", "Lower volatility than global equities")
    pdf.table_row("Ethical Objective", "100% Charter-compliant portfolio")
    pdf.table_row("Time Horizon", "Rolling 5-year periods")
    pdf.body("The CPI + 3.5% benchmark reflects the fund's absolute return orientation and real wealth preservation objective. The slightly lower target than growth-oriented peers (CPI + 4-5%) acknowledges the constraint of the ethical screen, which narrows the investable universe.")
    pdf.body("Benchmark appropriateness: (1) absolute return target is consistent with the fund's diversified, moderate-risk profile, (2) CPI linkage ensures inflation protection, (3) the 3.5% real premium is achievable within ethical constraints based on 10+ year evidence. The benchmark has been used since the fund's inception in January 2002 with no changes.")

    pdf.add_page()
    pdf.section("5. Key Personnel")
    pdf.subsection("Mark Simons -- Chief Investment Officer")
    pdf.body("Mark Simons has served as CIO of Australian Ethical since 2019. He has over 20 years of investment management experience, having previously held senior portfolio management roles at Colonial First State and AMP Capital. Mark holds a Master of Applied Finance and is a CFA charterholder.")
    pdf.subsection("Investment Team")
    pdf.body("The investment team comprises 14 professionals:")
    pdf.bullet("CIO + 3 senior portfolio managers (equities, fixed income, multi-asset)")
    pdf.bullet("4 investment analysts (sector coverage)")
    pdf.bullet("3 Ethics Research team members (Charter application, engagement)")
    pdf.bullet("2 quantitative analysts")
    pdf.bullet("1 portfolio implementation specialist")
    pdf.table_row("Average tenure", "6.8 years")
    pdf.table_row("Average experience", "14 years")
    pdf.body("Key person: Mark Simons is identified as the key person. The Ethics Research team is uniquely important as they interpret and apply the Charter. Succession: The Head of Ethics Research (12 years at AEF) and Deputy CIO are designated successors. The team's small size relative to peers is mitigated by deep institutional knowledge of the Charter and documented ethical assessment processes.")

    pdf.add_page()
    pdf.section("6. ESG Integration & Ethical Framework")
    pdf.body("ESG integration is not an 'add-on' for Australian Ethical -- it is the core of the investment process, enshrined in the founding Charter since 1986.")
    pdf.subsection("UNPRI & Industry Commitments")
    pdf.bullet("UNPRI signatory since 2007 (A+ Strategy & Governance)")
    pdf.bullet("Responsible Investment Association Australasia (RIAA) member")
    pdf.bullet("Climate Action 100+ participant")
    pdf.bullet("Net Zero Asset Managers Initiative signatory (2050 target)")
    pdf.bullet("TCFD supporter and reporter since 2019")
    pdf.bullet("TNFD early adopter (2023)")
    pdf.subsection("Ethical Scoring Methodology")
    pdf.body("The proprietary Ethical Scoring framework assesses companies across 23 impact categories:")
    pdf.bullet("Positive impacts: renewable energy, healthcare access, education, sustainable agriculture, financial inclusion, circular economy")
    pdf.bullet("Negative impacts: fossil fuels, weapons, tobacco, gambling, animal cruelty, deforestation, human rights violations, tax avoidance")
    pdf.body("Each company receives a net impact score from -10 (severe harm) to +10 (transformative benefit). Only companies with positive net scores are eligible for investment.")
    pdf.subsection("Exclusion List")
    pdf.body("Absolute exclusions (0% revenue threshold): Controversial weapons, cluster munitions, nuclear weapons, tobacco manufacturing, live animal export, old-growth logging, intensive factory farming.")
    pdf.body("Revenue-based exclusions: Fossil fuel extraction (>0%), fossil fuel power generation (>10%), gambling (>5%), alcohol manufacturing (>10%).")
    pdf.subsection("Engagement & Stewardship")
    pdf.body("Active engagement with all portfolio companies on material ESG issues. In FY2025:")
    pdf.bullet("Engaged with 92 companies on 148 topics")
    pdf.bullet("Filed 3 shareholder resolutions (all climate-related)")
    pdf.bullet("Voted on 100% of proxy resolutions")
    pdf.bullet("Voted against management on 24% of resolutions")
    pdf.bullet("Published detailed voting and engagement records quarterly")

    pdf.add_page()
    pdf.section("7. Conflicts of Interest")
    pdf.body("Australian Ethical's conflicts management:")
    pdf.bullet("Related parties: The fund invests primarily in its own managed sub-strategies. Fee rebates eliminate double-charging. All related-party transactions disclosed in annual report.")
    pdf.bullet("Personal trading: Investment staff subject to pre-clearance, 30-day hold, and prohibition on trading names under active research. The Charter applies to personal investments too -- staff may not personally hold securities excluded by the Charter.")
    pdf.bullet("Soft dollars: Not accepted. Research funded from firm resources.")
    pdf.bullet("Board independence: 6 directors, 4 independent. Board Chair is independent.")
    pdf.bullet("Ethical advisory: An independent Ethics Advisory Committee (3 external members) provides guidance on Charter interpretation, reducing conflicts in ethical assessments.")

    pdf.add_page()
    pdf.section("8. Fees & Costs")
    pdf.table_row("Management Fee (MER)", "0.79% p.a. of NAV")
    pdf.table_row("Indirect Cost Ratio (ICR)", "0.10% p.a.")
    pdf.table_row("Performance Fee", "Nil")
    pdf.table_row("Buy Spread", "0.12%")
    pdf.table_row("Sell Spread", "0.12%")
    pdf.table_row("Entry/Exit Fees", "Nil")
    pdf.body("The MER includes the cost of the Ethics Research team and impact measurement infrastructure, which is unique to Australian Ethical's approach. The ICR reflects costs of underlying strategies where used.")
    pdf.body("Total estimated cost: 0.89% p.a. plus applicable buy/sell spread. The higher cost relative to mainstream balanced funds reflects the intensive ethical research and engagement program that differentiates the fund.")

    pdf.add_page()
    pdf.section("9. Business Viability")
    pdf.table_row("Fund AUM", "AUD 870 million")
    pdf.table_row("Fund Inception", "1 January 2002")
    pdf.table_row("APIR Code", "AEF0003AU")
    pdf.table_row("Firm Total AUM", "AUD 10.7 billion")
    pdf.table_row("3-Year AUM Growth (firm)", "+18.5% CAGR")
    pdf.table_row("Staff Turnover", "15%")
    pdf.body("Australian Ethical has been one of the fastest-growing investment managers in Australia, benefiting from the secular trend toward ethical and sustainable investing. The firm's AUM has grown from AUD 3.8 billion in 2020 to AUD 10.7 billion in 2025, driven by strong retail and superannuation inflows.")
    pdf.body("The firm is publicly listed (ASX: AEF) providing governance transparency. Revenue growth has tracked AUM growth, and the firm is consistently profitable. No wind-down risk indicators.")
    pdf.subsection("AUM Trend")
    pdf.table_row("Dec 2023", "AUD 7.2 billion")
    pdf.table_row("Dec 2024", "AUD 9.1 billion")
    pdf.table_row("Dec 2025", "AUD 10.7 billion")

    # Pad to ~22 pages
    for i in range(12):
        pdf.add_page()
        if i == 0:
            pdf.section("10. The Australian Ethical Charter")
            pdf.body("The Australian Ethical Charter is the founding document that governs all investment decisions. It is embedded in the company's constitution. Key principles:")
            pdf.bullet("Shall seek to invest in activities and companies that the firm regards as making a positive contribution to human wellbeing and the environment")
            pdf.bullet("Shall avoid investment in activities and companies that are considered to unnecessarily exploit, damage, or threaten life or wellbeing")
            pdf.body("The Charter is interpreted by the Ethics Research team and guided by the independent Ethics Advisory Committee. Interpretation evolves with societal norms -- for example, fossil fuel exclusions were tightened in 2020 to include any exploration or extraction activity.")
        elif i == 1:
            pdf.section("11. Risk Disclosures")
            pdf.bullet("Market risk: Equity and bond markets can be volatile")
            pdf.bullet("Ethical screen risk: The reduced investable universe may result in higher concentration or different sector exposures vs mainstream peers")
            pdf.bullet("Tracking error: Performance may diverge significantly from mainstream benchmarks due to ethical exclusions")
            pdf.bullet("Manager risk: Active management may underperform")
            pdf.bullet("Climate transition risk: While the fund avoids fossil fuels, rapid transition may still affect other holdings")
        elif i == 2:
            pdf.section("12. Regulatory Information")
            pdf.bullet("AFSL 229949 -- current, good standing")
            pdf.bullet("ARSN 097 590 560")
            pdf.bullet("No enforceable undertakings (ever)")
            pdf.bullet("No material regulatory actions")
            pdf.bullet("AFCA member")
            pdf.body("Australian Ethical has maintained a clean regulatory record since its founding in 1986 -- nearly 40 years without a significant regulatory action.")
        elif i == 3:
            pdf.section("13. Climate Commitments")
            pdf.body("Australian Ethical's climate commitments:")
            pdf.bullet("Net Zero Asset Managers Initiative signatory -- portfolio Net Zero by 2050, interim targets for 2030")
            pdf.bullet("Zero fossil fuel exposure (extraction, power generation)")
            pdf.bullet("Portfolio carbon intensity: 65% below mainstream benchmark")
            pdf.bullet("Annual TCFD report published since 2019")
            pdf.bullet("Climate scenario analysis (1.5C, 2C, 3C pathways) conducted annually")
        elif i == 4:
            pdf.section("14. Impact Reporting")
            pdf.body("Australian Ethical publishes annual impact reports quantifying the real-world outcomes of its investments:")
            pdf.bullet("Tonnes of CO2 avoided through renewable energy investments")
            pdf.bullet("Number of people provided healthcare/education access")
            pdf.bullet("Hectares of biodiversity protected")
            pdf.bullet("Clean energy generation capacity funded (MW)")
            pdf.body("Impact measurement follows the Impact Management Project (IMP) framework and is independently assured by Deloitte.")
        elif i == 5:
            pdf.section("15. Governance")
            pdf.bullet("Board: 6 directors, 4 independent")
            pdf.bullet("Ethics Advisory Committee: 3 external experts")
            pdf.bullet("Investment Committee: CIO + 3 senior PMs")
            pdf.bullet("Risk & Compliance Committee: 3 independent directors")
            pdf.bullet("External auditor: Deloitte")
        elif i == 6:
            pdf.section("16. Withdrawals")
            pdf.body("Daily redemptions processed within 5 business days. No gates or notice periods under normal conditions. The fund maintains 10%+ in cash/near-cash to support liquidity requirements.")
        elif i == 7:
            pdf.section("17. Taxation")
            pdf.body("AMIT regime. Semi-annual distributions (June and December) comprising dividends, interest, franking credits, and capital gains. AMMA statements provided for tax reporting.")
        elif i == 8:
            pdf.section("18. Minimum Investment")
            pdf.table_row("Minimum Initial", "AUD 1,000")
            pdf.table_row("Minimum Additional", "AUD 100")
            pdf.body("Low minimums reflect the firm's commitment to making ethical investing accessible to all Australians.")
        elif i == 9:
            pdf.section("19. Compliance Framework")
            pdf.bullet("CCO reports directly to Board")
            pdf.bullet("Compliance team: 5 professionals")
            pdf.bullet("Annual compliance plan (approved January 2026)")
            pdf.bullet("Automated portfolio monitoring against Charter and investment limits")
            pdf.bullet("Breach register: 1 minor breach in past 3 years (one-day over-allocation to a single stock, self-identified, corrected immediately)")
        elif i == 10:
            pdf.section("20. Superannuation")
            pdf.body("Australian Ethical also operates a superannuation fund (Australian Ethical Super) which invests in the same strategies. The Balanced Fund is available both directly and through super, with consistent ethical screening applied across all channels.")
        else:
            pdf.section("21. Contact")
            pdf.body("Australian Ethical Investment Limited")
            pdf.body("Phone: 1800 021 227")
            pdf.body("Email: enquiries@australianethical.com.au")
            pdf.body("Website: www.australianethical.com.au")

    pdf.save("pf_aef001_pds.pdf")


def gen_esg():
    pdf = DocPDF("Australian Ethical - ESG Impact Report 2025")
    pdf.cover_page("Australian Ethical Investment", "ESG Impact Report 2025\nMeasuring Real-World Outcomes", "December 2025", "Australian Ethical Investment Limited")

    pdf.add_page()
    pdf.section("About This Report")
    pdf.body("This report presents the environmental, social, and governance outcomes of Australian Ethical's investment activities for the financial year ended 30 June 2025. Impact metrics follow the Impact Management Project (IMP) framework and are independently assured by Deloitte.")
    pdf.body("Australian Ethical has been a UNPRI signatory since 2007 and received an A+ rating for Strategy & Governance in the most recent PRI assessment. The firm is a founding signatory to the Net Zero Asset Managers Initiative and reports annually under the TCFD framework.")

    pdf.add_page()
    pdf.section("ESG Integration -- How We Invest")
    pdf.body("ESG integration at Australian Ethical is not a separate overlay -- it is the core of our investment philosophy, mandated by the Australian Ethical Charter since 1986.")
    pdf.subsection("Ethical Scoring Framework")
    pdf.body("Every potential and existing investment is assessed using our proprietary Ethical Scoring framework across 23 impact categories. The framework evaluates both positive contributions (benefits) and negative impacts (harms).")
    pdf.body("Scoring methodology: Each company is scored from -10 (severe harm) to +10 (transformative positive impact) across relevant categories. Only companies with a positive net score are eligible for investment. The scoring is conducted by the dedicated Ethics Research team (3 specialists) and reviewed by the independent Ethics Advisory Committee.")
    pdf.subsection("Screening Results (FY2025)")
    pdf.table_row("Universe screened", "~4,500 global companies")
    pdf.table_row("Excluded (Charter breach)", "~1,800 companies (40%)")
    pdf.table_row("Eligible universe", "~2,700 companies")
    pdf.table_row("Currently invested", "~320 companies")

    pdf.add_page()
    pdf.section("Environmental Impact")
    pdf.subsection("Climate")
    pdf.table_row("Portfolio carbon intensity", "52 tCO2e/$M revenue")
    pdf.table_row("Benchmark carbon intensity", "148 tCO2e/$M revenue")
    pdf.table_row("Carbon intensity reduction", "-65% vs benchmark")
    pdf.table_row("Fossil fuel exposure", "0% (zero)")
    pdf.table_row("Renewable energy invested", "AUD 1.2 billion")
    pdf.table_row("Clean energy capacity funded", "1,840 MW")
    pdf.table_row("CO2 avoided (renewable inv.)", "2.3 million tonnes p.a.")
    pdf.subsection("Biodiversity")
    pdf.table_row("Deforestation-free portfolio", "Yes (verified)")
    pdf.table_row("TNFD-aligned disclosure", "Published 2024")
    pdf.table_row("Biodiversity-positive inv.", "AUD 280 million")

    pdf.add_page()
    pdf.section("Social Impact")
    pdf.table_row("Healthcare companies invested", "AUD 890 million")
    pdf.table_row("Education companies invested", "AUD 340 million")
    pdf.table_row("Affordable housing funded", "AUD 120 million")
    pdf.table_row("Financial inclusion invest.", "AUD 210 million")
    pdf.body("Our social impact extends beyond direct investments. Through active engagement, we have:")
    pdf.bullet("Advocated for improved modern slavery disclosure at 28 companies")
    pdf.bullet("Pushed for gender diversity targets at 15 companies (12 adopted)")
    pdf.bullet("Engaged on Indigenous reconciliation with 8 Australian companies")

    pdf.add_page()
    pdf.section("Governance & Stewardship")
    pdf.subsection("Proxy Voting (FY2025)")
    pdf.table_row("Resolutions voted", "4,218 (100% of eligible)")
    pdf.table_row("Voted against management", "24%")
    pdf.table_row("Remuneration: against", "38%")
    pdf.table_row("Board composition: against", "22%")
    pdf.table_row("Climate resolutions: for", "100%")
    pdf.subsection("Engagement")
    pdf.table_row("Companies engaged", "92")
    pdf.table_row("Engagement topics", "148")
    pdf.table_row("Shareholder resolutions filed", "3 (all climate)")
    pdf.body("Key engagement themes in FY2025: climate transition plans, nature/biodiversity commitments, supply chain labour standards, executive remuneration alignment with sustainability targets, and tax transparency.")
    pdf.subsection("Engagement Outcomes")
    pdf.body("Of 148 engagement topics, 43 (29%) resulted in positive company action within FY2025. Key wins included:")
    pdf.bullet("4 companies adopted science-based climate targets following our engagement")
    pdf.bullet("3 companies improved modern slavery reporting")
    pdf.bullet("2 companies linked executive remuneration to emissions reduction targets")

    pdf.add_page()
    pdf.section("Exclusions & Negative Screening")
    pdf.body("Companies excluded from the portfolio under the Charter:")
    pdf.subsection("Absolute Exclusions (zero tolerance)")
    pdf.bullet("Controversial weapons, cluster munitions, nuclear weapons")
    pdf.bullet("Tobacco manufacturing")
    pdf.bullet("Live animal export")
    pdf.bullet("Old-growth logging")
    pdf.bullet("Intensive factory farming")
    pdf.subsection("Revenue-Based Exclusions")
    pdf.table_row("Fossil fuel extraction", ">0% revenue")
    pdf.table_row("Fossil fuel power gen.", ">10% revenue")
    pdf.table_row("Gambling", ">5% revenue")
    pdf.table_row("Alcohol manufacturing", ">10% revenue")
    pdf.table_row("Pornography", ">0% revenue")
    pdf.table_row("Predatory lending", ">5% revenue")
    pdf.body("Exclusion list is reviewed annually by the Ethics Advisory Committee. Thresholds were tightened in FY2025 for fossil fuel power generation (from 15% to 10%).")

    pdf.add_page()
    pdf.section("Net Zero Commitment & Progress")
    pdf.body("Australian Ethical is a signatory to the Net Zero Asset Managers Initiative with the following targets:")
    pdf.table_row("Portfolio Net Zero target", "2050")
    pdf.table_row("Interim target (2030)", "-50% portfolio emissions intensity")
    pdf.table_row("Progress (FY2025)", "-42% vs 2020 baseline (on track)")
    pdf.body("Approach: We achieve Net Zero alignment through: (1) exclusion of fossil fuels, (2) positive investment in climate solutions, (3) engagement with portfolio companies on transition plans, and (4) annual portfolio decarbonisation review.")
    pdf.body("Note: The fund has never held fossil fuel investments due to the Charter. Our Net Zero journey focuses on reducing Scope 3 emissions of portfolio companies and increasing climate solutions allocation.")

    pdf.add_page()
    pdf.section("TCFD Disclosure Summary")
    pdf.body("Governance: Board-level oversight of climate risk via Risk & Compliance Committee. CIO responsible for climate integration in investment process. Annual TCFD report published since 2019.")
    pdf.body("Strategy: Climate scenario analysis conducted annually (1.5C, 2C, 3C pathways). Portfolio stress-tested against transition and physical risk scenarios. Energy transition investments identified as growth opportunity.")
    pdf.body("Risk Management: Climate risk integrated into Ethical Scoring framework. Carbon intensity monitored quarterly. Companies without credible transition plans are candidates for divestment.")
    pdf.body("Metrics & Targets: Portfolio WACI, fossil fuel exposure (zero), green revenue share, climate solutions allocation. All metrics disclosed in this report and the annual TCFD report.")

    pdf.add_page()
    pdf.section("SDG Alignment")
    pdf.body("Portfolio alignment with UN Sustainable Development Goals:")
    pdf.table_row("SDG 3 (Health)", "15% of portfolio")
    pdf.table_row("SDG 4 (Education)", "6% of portfolio")
    pdf.table_row("SDG 7 (Clean Energy)", "12% of portfolio")
    pdf.table_row("SDG 9 (Innovation)", "18% of portfolio")
    pdf.table_row("SDG 11 (Sustainable Cities)", "8% of portfolio")
    pdf.table_row("SDG 13 (Climate Action)", "14% of portfolio")
    pdf.body("Total portfolio with positive SDG alignment: 73%")

    pdf.add_page()
    pdf.section("Independent Assurance")
    pdf.body("Selected impact metrics in this report have been subject to limited assurance by Deloitte Touche Tohmatsu. The assurance covers: carbon intensity calculations, fossil fuel exposure verification, exclusion compliance, and proxy voting statistics.")
    pdf.body("Deloitte's assurance opinion (October 2025): 'Nothing has come to our attention that causes us to believe the selected metrics are not prepared, in all material respects, in accordance with the stated methodology.'")

    pdf.add_page()
    pdf.section("Looking Ahead -- FY2026 Priorities")
    pdf.bullet("Deepen TNFD (nature) reporting and set nature-positive targets")
    pdf.bullet("Increase climate solutions allocation to 30% of portfolio")
    pdf.bullet("Expand engagement program to cover Scope 3 emissions at top 50 holdings")
    pdf.bullet("Publish first standalone Human Rights report")
    pdf.bullet("Strengthen Indigenous engagement framework")
    pdf.body("Australian Ethical remains committed to demonstrating that ethical investing can deliver competitive financial returns while creating measurable positive impact for people and planet.")

    pdf.save("pf_aef001_esg.pdf")


def gen_ddq():
    pdf = DocPDF("Australian Ethical Balanced - DDQ Response")
    pdf.cover_page("Australian Ethical Investment", "Due Diligence Questionnaire Response\nAustralian Ethical Balanced Fund", "March 2026", "Australian Ethical Investment Limited")

    pdf.add_page()
    pdf.section("1. Risk Management Framework")
    pdf.body("Australian Ethical operates a risk framework covering both financial and ethical risk:")
    pdf.subsection("Risk Governance")
    pdf.bullet("Board Risk & Compliance Committee: 3 independent directors, meets quarterly")
    pdf.bullet("Investment Risk Committee: CIO + Head of Risk + senior PMs, meets monthly")
    pdf.bullet("Ethics Advisory Committee: 3 external experts, meets quarterly")
    pdf.bullet("Independent risk function: 4 professionals, CRO reports to Board")
    pdf.subsection("Quantitative Risk Limits")
    pdf.table_row("Portfolio VaR (95%, 1-day)", "Limit: 0.8% of NAV")
    pdf.table_row("CVaR (95%, 1-day)", "Limit: 1.2% of NAV")
    pdf.table_row("Tracking Error vs SAA", "Hard limit: 6% p.a.")
    pdf.table_row("Single Stock Limit", "6% at cost")
    pdf.table_row("Drawdown Trigger", "-12% from peak triggers IC review")
    pdf.body("Ethical risk management: Any Charter breach identified in an existing holding triggers immediate escalation to the Ethics Research team. Confirmed breaches require divestment within 30 days. Near-misses are tracked and reported to the Ethics Advisory Committee quarterly.")
    pdf.body("Escalation: Financial risk limit breaches notified to CRO within 4 hours. Ethical breaches escalated to Head of Ethics Research immediately. Board notification for any material breach within 24 hours.")

    pdf.add_page()
    pdf.section("2. Operational Infrastructure")
    pdf.subsection("Service Providers")
    pdf.table_row("Custodian", "BNP Paribas Securities Services (APRA-regulated)")
    pdf.table_row("Administrator", "BNP Paribas (unit pricing, accounting)")
    pdf.table_row("Registry", "Automic Group")
    pdf.table_row("External Auditor", "Deloitte Touche Tohmatsu")
    pdf.subsection("Technology Systems")
    pdf.table_row("OMS/PMS", "SimCorp Dimension")
    pdf.table_row("Risk System", "FactSet")
    pdf.table_row("Compliance", "FIS Protegent (automated)")
    pdf.table_row("Ethical Screening", "Proprietary Charter-compliance system")
    pdf.table_row("Reconciliation", "Daily automated (BNP Paribas)")
    pdf.subsection("Audit & Controls")
    pdf.body("Most recent external audit (30 June 2025): Unqualified opinion by Deloitte.")
    pdf.body("ISAE 3402 report from BNP Paribas (December 2025): No exceptions noted.")
    pdf.body("Internal audit: Annual review cycle covering investment operations, ethical screening, and technology. Most recent: All satisfactory.")

    pdf.add_page()
    pdf.section("3. Key Person Risk & Team")
    pdf.body("Mark Simons (CIO) is identified as the key person. Additionally, the Ethics Research team's institutional knowledge of Charter interpretation is considered critical. Mitigation:")
    pdf.bullet("Deputy CIO designated with full authority in CIO's absence")
    pdf.bullet("Head of Ethics Research (12 years tenure) can independently run ethical screening")
    pdf.bullet("All Charter interpretations documented in precedent database (800+ decisions)")
    pdf.bullet("Ethics Advisory Committee provides external continuity")
    pdf.subsection("Team Depth")
    pdf.table_row("Total investment team", "14 professionals")
    pdf.table_row("Ethics Research team", "3 specialists")
    pdf.table_row("Average tenure", "6.8 years")
    pdf.table_row("Turnover (3yr avg)", "15%")
    pdf.body("The 15% turnover is slightly above industry average, partly reflecting the firm's rapid growth requiring capability expansion. No senior investment departures in the past 2 years. Staff attracted by alignment with ethical mission; retention programs include competitive remuneration and purpose-driven culture.")

    pdf.add_page()
    pdf.section("4. Business Continuity & DR")
    pdf.table_row("RTO", "4 hours for critical systems")
    pdf.table_row("RPO", "1 hour")
    pdf.table_row("DR Site", "Cloud-based (AWS), geographically redundant")
    pdf.table_row("Remote Trading", "All PMs can trade remotely")
    pdf.subsection("Testing")
    pdf.body("BCP/DR tested annually. Most recent (September 2025): Full DR activation achieved within 3.5 hours (within RTO). Ethical screening system tested separately and confirmed operational at DR site.")
    pdf.body("COVID experience: Successfully operated remotely March 2020 - July 2021. No trading disruptions. Experience validated remote infrastructure and led to permanent hybrid arrangements.")
    pdf.body("BCP reviewed annually by Board. Last full update: July 2025.")

    pdf.add_page()
    pdf.section("5. Compliance & Regulatory")
    pdf.body("AFSL 229949 is current with standard authorisations for operating MIS and providing financial advice.")
    pdf.bullet("Compliance team: 5 professionals, CCO reports to Board")
    pdf.bullet("Annual compliance plan (approved January 2026)")
    pdf.bullet("Automated compliance monitoring (Charter + investment limits)")
    pdf.bullet("Breach register: 1 minor breach in past 3 years (single-stock over-allocation by 0.3%, self-identified, corrected same day)")
    pdf.bullet("Zero significant breaches or ASIC actions in firm's 40-year history")
    pdf.bullet("AFCA member")
    pdf.body("The firm's unblemished 40-year regulatory record is notable and reflects the deep ethical culture that extends to compliance and operational conduct.")

    pdf.add_page()
    pdf.section("6. Conflicts of Interest")
    pdf.subsection("Related Party Transactions")
    pdf.body("The Balanced Fund invests in Australian Ethical's own sub-strategies (Australian Equities Fund, International Equities Fund, Fixed Income Fund). Fee rebates are applied to eliminate double-charging. All related investments are disclosed.")
    pdf.subsection("Personal Trading")
    pdf.bullet("Pre-clearance required for all personal trades")
    pdf.bullet("30-day minimum holding period")
    pdf.bullet("Charter applies to personal investments -- staff may not hold excluded stocks")
    pdf.bullet("Quarterly compliance certification")
    pdf.subsection("Independence")
    pdf.bullet("Board: 6 directors, 4 independent (Chair independent)")
    pdf.bullet("Ethics Advisory Committee: 3 external members, fully independent")
    pdf.bullet("No affiliated broker or custodian")
    pdf.bullet("Soft dollars: Not accepted")

    pdf.add_page()
    pdf.section("7. Business Viability")
    pdf.table_row("Firm Revenue (FY2025)", "AUD 98 million")
    pdf.table_row("Net Profit (FY2025)", "AUD 24 million")
    pdf.table_row("Total AUM (Dec 2025)", "AUD 10.7 billion")
    pdf.table_row("3-Year AUM CAGR", "+18.5%")
    pdf.table_row("Dividend Payout", "65% of earnings")
    pdf.subsection("Growth Trajectory")
    pdf.table_row("Dec 2023", "AUD 7.2 billion")
    pdf.table_row("Dec 2024", "AUD 9.1 billion")
    pdf.table_row("Dec 2025", "AUD 10.7 billion")
    pdf.body("Australian Ethical is one of the fastest-growing investment managers in Australia, with AUM nearly tripling in 5 years. Growth is driven by the secular trend toward ethical/sustainable investing, particularly in superannuation.")
    pdf.subsection("Staff")
    pdf.table_row("Total employees", "165")
    pdf.table_row("Investment professionals", "14")
    pdf.table_row("Voluntary turnover (2025)", "15%")
    pdf.body("The firm's rapid growth has required significant hiring across all functions. The investment team has been deliberately kept lean relative to AUM, with scale achieved through systematic processes and technology.")

    # Pad to ~18 pages
    for i in range(10):
        pdf.add_page()
        if i == 0:
            pdf.section("8. Technology & Cyber Security")
            pdf.bullet("Cloud-first architecture (AWS)")
            pdf.bullet("ISO 27001 certification in progress (target: Q2 2026)")
            pdf.bullet("Annual penetration testing (last: August 2025, no critical findings)")
            pdf.bullet("MFA on all systems")
            pdf.bullet("Managed SOC (24/7 monitoring)")
            pdf.bullet("Quarterly vulnerability assessments")
            pdf.bullet("Mandatory cyber training (phishing simulations monthly)")
        elif i == 1:
            pdf.section("9. Ethical Screening Technology")
            pdf.body("Australian Ethical has developed proprietary technology to support Charter compliance:")
            pdf.bullet("Automated daily screening of all holdings against exclusion criteria")
            pdf.bullet("Real-time alerts for potential Charter breaches (news monitoring)")
            pdf.bullet("Ethical Scoring database covering 4,500+ companies")
            pdf.bullet("Precedent database of 800+ Charter interpretation decisions")
            pdf.body("The system is maintained by a dedicated technology team and undergoes annual testing as part of the BCP/DR cycle.")
        elif i == 2:
            pdf.section("10. Proxy Voting Policy")
            pdf.body("Australian Ethical exercises all voting rights directly (no proxy advisor outsourcing):")
            pdf.bullet("All voting decisions made by Ethics Research team + relevant PM")
            pdf.bullet("Voting policy published on website")
            pdf.bullet("Quarterly disclosure of all votes (including rationale for against-votes)")
            pdf.bullet("Will vote against management on: inadequate climate targets, excessive executive pay, insufficient board diversity, poor human rights oversight")
        elif i == 3:
            pdf.section("11. Liquidity Management")
            pdf.bullet("Minimum 80% of portfolio realisable within 7 days")
            pdf.bullet("Quarterly liquidity stress testing")
            pdf.bullet("Cash/near-cash buffer: 10%+ maintained")
            pdf.bullet("No illiquid investments (property is via listed REITs only)")
            pdf.bullet("Large redemption protocol: >5% of fund triggers PM notification")
        elif i == 4:
            pdf.section("12. Insurance")
            pdf.bullet("Professional Indemnity: AUD 50 million")
            pdf.bullet("Directors & Officers: AUD 30 million")
            pdf.bullet("Crime/Fidelity: AUD 20 million")
            pdf.bullet("Cyber Insurance: AUD 15 million")
        elif i == 5:
            pdf.section("13. Counterparty Risk")
            pdf.body("Minimal counterparty exposure:")
            pdf.bullet("No OTC derivatives")
            pdf.bullet("Exchange-traded futures only (ASX Clear)")
            pdf.bullet("Custodian (BNP Paribas): APRA-regulated, S&P AA- rated")
            pdf.bullet("No securities lending")
        elif i == 6:
            pdf.section("14. Valuation")
            pdf.body("Listed securities: Daily market prices (ASX, international exchanges)")
            pdf.body("Fixed income: Independent pricing services (Bloomberg)")
            pdf.body("Unit pricing verified daily by BNP Paribas (administrator)")
            pdf.body("Valuation policy audited annually by Deloitte")
        elif i == 7:
            pdf.section("15. Distribution Policy")
            pdf.body("Semi-annual distributions (June and December). Comprising dividends, interest, franking credits, and capital gains. The fund aims to distribute 100% of taxable income.")
        elif i == 8:
            pdf.section("16. Regulatory & Legal Confirmations")
            pdf.bullet("AFSL 229949 current, no conditions")
            pdf.bullet("No current litigation")
            pdf.bullet("No pending regulatory actions")
            pdf.bullet("All reporting obligations met on time")
            pdf.bullet("AFCA member, no unresolved complaints")
        else:
            pdf.section("17. Appendix -- Ethical Charter (Extract)")
            pdf.body("The Australian Ethical Charter states that the trustee shall seek out investments which provide for and support:")
            pdf.bullet("The development of workers' participation in the ownership and control of their work organisations and places")
            pdf.bullet("The ## of self-reliance and respect for the natural environment among indigenous peoples")
            pdf.bullet("The production of safe and beneficial products and services")
            pdf.bullet("The efficient use of human waste and the recycling of materials")
            pdf.body("And shall avoid investments which unnecessarily:")
            pdf.bullet("Exploit people through the payment of low wages or the provision of poor conditions")
            pdf.bullet("Are unduly wasteful or polluting")
            pdf.bullet("Contribute to the destruction of wilderness areas or their native ecosystems")

    pdf.save("pf_aef001_ddq.pdf")


if __name__ == "__main__":
    print("Generating Australian Ethical Balanced Fund documents...")
    gen_pds()
    gen_esg()
    gen_ddq()
    print("Done!")
